### PR TITLE
No mixin forwarders for known binary incompatible trait overrides

### PR DESCRIPTION
**Pull request by lrytz**
New overrides added to traits are not forwards binary compatible
(scala/bug#12137).

For those overrides that were added since 2.12.0, a new special case
in Mixin avoids generating the mixin forwarder, so compiling with
2.12.13 will emit code that is binary compatible with 2.12.0.

Tested with this code:

```
object A extends scala.math.Ordering.IntOrdering   // `reverse` override was added
object B extends scala.math.Ordering.FloatOrdering // `reverse` override was removed

object Test {
  def main(args: Array[String]): Unit = {
    println(A.reverse)
    println(B.reverse)
  }
}
```

Code compiled with 2.12.13 (qsc/qs) works with all 2.12 libraries
thanks to this fix.

```
qsc Test.scala && sv 2.12.0 Test && sv 2.12.12 Test && qs Test
```

Code compiled with 2.12.0 fails on 2.12.12. The super call in the
generated mixin forwarder `B.reverse` invokes the static method
`FloatOrdering.reverse$` that no longer exists. This will be the same
in 2.12.13.

```
scv 2.12.0 Test.scala && sv 2.12.12 Test
java.lang.NoSuchMethodError: scala.math.Ordering$FloatOrdering.reverse$
```

### CODE REVIEW

**Comment by lrytz** [comment]
Ah interesting, with the bootstrapped compiler the change affects the scala library itself

```
+java.io.InvalidClassException: scala.math.Ordering$Int$; local class incompatible: stream classdesc serialVersionUID = -941572818022838553, local class serialVersionUID = 7046738597064095034
```

**Review by dwijnand — APPROVED** [review]
Sad, but pragmatic...

**Comment by lrytz** [comment]
I still want to convince myself that this PR does not create new binary incompatibilities (because some mixin forwarders that were previously emitted no longer are).

**Comment by lrytz** [comment]
Finally coming back to this. Adding a full example for discussion.

In 2.12.0 we had

```scala
trait Ordering {
  def reverse: Ordering = ...
}
trait IntOrdering extends Ordering
object Int extends IntOrdering
```

In `Int$.class`, there's a `reverse()Ordering` mixin forwarder method with `INVOKESTATIC Ordering.reverse$`.

The definition changed (in 44318c8959b3ce48a44d3c0692e87fa7dfbb8930) to

```scala
trait Ordering {
  def reverse: Ordering = ...
}
trait IntOrdering extends Ordering {
  override def reverse: Ordering = ...
}
object Int extends IntOrdering
```

Now, the mixin forwarder in `Int$.class` calls `INVOKESTATIC Ordering$IntOrdering.reverse`, which is not forwards compatible (that method doesn't exist in a 2.12.0 standard library).

After this PR the compiler avoids emitting mixin forwarders to `Ordering$IntOrdering.reverse`. This restores binary compatibility (an `INVOKEVIRTUAL Int$.reverse()Ordering` is still valid because `Int$` inherits a default method with the right signature). However, removing the method changes the auto-generated serial version UID (even if it doesn't affect serialization compatibility per se, see https://github.com/scala/scala-dev/issues/237).

```scala
2.12.0 and 2.12.12:
scala> java.io.ObjectStreamClass.lookup(scala.math.Ordering.Int.getClass).getSerialVersionUID
res0: Long = -941572818022838553


This PR after bootstrap:
scala> java.io.ObjectStreamClass.lookup(scala.math.Ordering.Int.getClass).getSerialVersionUID
res0: Long = 7046738597064095034
```

For the standard library, we can find all subclasses of affected traits and put their 2.12.12 `@SerialVersionUID` on them. However, user-defined classes that extend these traits are also affected.

So I'm having doubts that adding this (potential) breakage is worth it, especially in 2.12.

**Comment by dwijnand** [comment]
> ```scala
> 2.12.0 and 2.12.12:
> scala> java.io.ObjectStreamClass.lookup(scala.math.Ordering.Int.getClass).getSerialVersionUID
> res0: Long = -941572818022838553
> ```

If 2.12.12 added the method override how does it have the same SerialVersionUID?

(I double-checked it wasn't a typo, but it really is the same! 😕)

```scala
$ scala -nc -2.12.0 -e 'println(java.io.ObjectStreamClass.lookup(scala.math.Ordering.Int.getClass).getSerialVersionUID)'
-941572818022838553
$ scala -nc -2.12.12 -e 'println(java.io.ObjectStreamClass.lookup(scala.math.Ordering.Int.getClass).getSerialVersionUID)'
-941572818022838553
```

**Comment by lrytz** [comment]
> If 2.12.12 added the method override how does it have the same SerialVersionUID?

The mixin forwarder in `Int$` was always there, back to 2.12.0. The implementation of the mixin forwarder changed ~in 2.12.12~ along the way, before it used to call `INVOKESTATIC Ordering.reverse$`, then it changed to `Ordering$IntOrdering.reverse`.

**Comment by dwijnand** [comment]
So instead of eliding we should pin these forwarders to their old location (`Ordering.reverse$`)?

**Comment by lrytz** [comment]
That would work, though it would mean regressing performance, the overrides would no longer be used. You could argue that adding the overrides would not have been allowed in the first place. On the other hand, noone bumped into any of the binary incompatibilities that are adressed here (https://github.com/scala/bug/issues/12137 was about a case in 2.13.x), and they've been around for multiple minor versions. So I think my preference is to leave things as is in 2.12, maybe also 2.13.

**Comment by lrytz** [comment]
We decided to go ahead with this change, a serialization incompatibility is less likely to affect users.

**Comment by dwijnand** [comment]
How does a user retrieve their current default `@SerialVersionUID` value, so they can pin it when they upgrade?

**Comment by dwijnand** [comment]
```
[error] scala-library: Failed binary compatibility check against org.scala-lang:scala-library:2.12.0! Found 16 potential problems (filtered 858)
[error]  * method reverse()scala.math.Ordering in object scala.math.Ordering#Int does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.math.Ordering#Int.reverse")
[error]  * method reverse()scala.math.Ordering in object scala.math.Numeric#IntIsIntegral does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.math.Numeric#IntIsIntegral.reverse")
[error]  * method last()java.lang.Object in class scala.collection.SeqViewLike#AbstractTransformed does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.SeqViewLike#AbstractTransformed.last")
[error]  * method last()java.lang.Object in class scala.collection.IterableViewLike#AbstractTransformed does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.IterableViewLike#AbstractTransformed.last")
[error]  * method last()java.lang.Object in class scala.collection.TraversableViewLike#AbstractTransformed does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.TraversableViewLike#AbstractTransformed.last")
[error]  * method toList()scala.collection.immutable.List in class scala.collection.immutable.StringOps does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.StringOps.toList")
[error]  * method toList()scala.collection.immutable.List in class scala.collection.mutable.ArrayOps#ofChar does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.ArrayOps#ofChar.toList")
[error]  * method toList()scala.collection.immutable.List in class scala.collection.mutable.ArrayOps#ofShort does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.ArrayOps#ofShort.toList")
[error]  * method toList()scala.collection.immutable.List in class scala.collection.mutable.ArrayOps#ofUnit does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.ArrayOps#ofUnit.toList")
[error]  * method toList()scala.collection.immutable.List in class scala.collection.mutable.ArrayOps#ofInt does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.ArrayOps#ofInt.toList")
[error]  * method toList()scala.collection.immutable.List in class scala.collection.mutable.ArrayOps#ofBoolean does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.ArrayOps#ofBoolean.toList")
[error]  * method toList()scala.collection.immutable.List in class scala.collection.mutable.ArrayOps#ofDouble does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.ArrayOps#ofDouble.toList")
[error]  * method toList()scala.collection.immutable.List in class scala.collection.mutable.ArrayOps#ofRef does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.ArrayOps#ofRef.toList")
[error]  * method toList()scala.collection.immutable.List in class scala.collection.mutable.ArrayOps#ofByte does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.ArrayOps#ofByte.toList")
[error]  * method toList()scala.collection.immutable.List in class scala.collection.mutable.ArrayOps#ofLong does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.ArrayOps#ofLong.toList")
[error]  * method toList()scala.collection.immutable.List in class scala.collection.mutable.ArrayOps#ofFloat does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.ArrayOps#ofFloat.toList")
```

```
% scalac t8549.scala
% <in process execution of run/t8549.scala> > t8549-run.log
% diff /home/jenkins/workspace/scala-2.12.x-validate-main@2/test/files/run/t8549.check /home/jenkins/workspace/scala-2.12.x-validate-main@2/test/files/run/t8549-run.log
@@ -1 +1,52 @@
 warning: two deprecations (since 2.11.0); re-run with -deprecation for details
+java.io.InvalidClassException: scala.math.Ordering$Int$; local class incompatible: stream classdesc serialVersionUID = -941572818022838553, local class serialVersionUID = 7046738597064095034
```

**Comment by lrytz** [comment]
Two more observations here.

---

1. If the new trait override uses a `super` call, the trait gets a corresponding abstract super accessor method. Example

```scala
trait T { def f = 1 }
trait U extends T { override def f = super.f + 1 }
```

This leads to a new binary incompatibility: when compiling `class C extends U` on an old version (where `f` is not overridden in `U`), but running on a new version where `U` has an abstract super accessor, `C` doesn't implement this accessor. This was detected by MiMa and explicitly excluded in 11f93da364, but I'm not 100% sure it's safe. For example
  - Compile `trait T { def f = 1 }; trait U extends T`
  - Compile `class C extends U` with `-Xmixin-force-forwarders:false`, then `C` has no mixin forwarder and no super accessor implementation
  - Add the override and re-compile `T` and `U`
  - Run `(new C).f`. That resolves to `U.f`, which calls the super accessor, but that's abstract in `C`

Without `-Xmixin-force-forwarders:false` it works, because the mixin forwarder in `C` calls `T.f$`, so the super accessor is never used, and the `AbstractMethodError` is not triggered.

From the list of trait methods in this PR, `SortedSet.equals` and `immutable.equals` use a super call.

---

2. We cannot omit the mixin forwarder for trait methods that override a method from a superclass. This applies to `immutable.SortedSet.equals` and `immutable.SortedMap.equals`. Subclasses of `SortedSet`/`SortedMap` *need* the mixin forwarder, otherwise method resolution picks the method in the superclass (`Object.equals`) over the default method.

We cannot remove the `SortedSet.equals` override, because it removes its static accessor which may be used in existing published libraries.

We could special-case the comiler to rewire `super[SortedSet].equals` calls to `super[GenSetLike].equals`. This would render the optimized `SortedSet.equals` unused. We could restore the optimization by adding overrides in concrete classes.

I feel that it's slowly getting too complex though...

**Comment by retronym** [comment]
> Without `-Xmixin-force-forwarders:false` it works

It does't exhibit a linkage error but it also fails to pick up the new behaviour in `U`. This suggests that the default of true for `Xmixin-force-forwarders` is a poor choice for binary compatibility.

**Comment by retronym** [comment]
One option we have for `Sorted{Set,Map}.equals` would be to inline the `super.equals` call (with `: @inline` or by hand):

https://github.com/scala/scala/pull/9311

**Comment by lrytz** [comment]
Pushed a change that implements "Option 2" from Dale's list: https://github.com/scala/bug/issues/12137#issuecomment-724580405: continue to emit mixin forwarders, but sidestep the incompatible overrides. We can bring back the optimized code by pushing it down into subclasses.

The advantages are that it works in all cases (also for `equals`), there are no changes to signatures, and it works for all super calls, not only those in mixin forwarders.

**Comment by lrytz** [comment]
With MiMa exceptions this can be turned into ✅.

@retronym wdyt? To me it looks pretty unpleasant overall...

**Comment by dwijnand** [comment]
We decided it's getting too hairy and too complicated.  To go back to how this manifests: if you compile with a newer standard library and use an old standard library, then you get a linkage error (eg NoSuchMethodError).  The root cause was we weren't checking for that in MiMA and now we are.  As time goes on it becomes less and less likely that a user is consuming a library built with 2.12.20 while still being on 2.12.10 (and even so they need to hit the specific methods that we accidentally defined).
