### PR TITLE
Merge/2.12.x to 2.13.x 20170717 [ci: last-only]

### PR DESCRIPTION
**Pull request by szeiger**
Conflicts mostly due to REPL refactoring. Who's the best candidate to review this in lieu of @adriaanm? @retronym perhaps?

```
$ git checkout -b merge/2.12.x-to-2.13.x-20170717 scala/2.13.x

$ export MB=$(git merge-base HEAD scala/2.12.x)

$ git log --graph --oneline --decorate $MB..scala/2.12.x
*   9ab72a204f (scala/2.12.x) Merge pull request #5989 from lrytz/inline-from-sources
|\
| * 124bee7def -opt-inline-from:<sources> to allow inlining from compilation units
* |   36bf2a9104 Merge pull request #5942 from Atry/patch-8
|\ \
| * | b886a875e0 Set max-width for subpackage-spacer
|  /
* |   38be47af1e Merge pull request #5770 from som-snytt/issue/6714
|\ \
| * | 645738267c SI-6714 Preserve implicit args in update assign
| * | 91124eda54 SI-6714 Update assignment preserves apply args
|  /
* |   6e7c960168 Merge pull request #5985 from retronym/ticket/10205
|\ \
| * | a1f0d629e2 (retronym/ticket/10205) Test case for recently fixed bug
| |/
* |   ccfba35fc4 Merge pull request #5986 from retronym/ticket/9146
|\ \
| |/
|/|
| * 1c7bb21abd (retronym/ticket/9146) Test case for already-fixed pattern matcher bug
|/
*   cc7ba86bc6 (retronym/2.12.x) Merge pull request #5979 from retronym/topic/disable-tag-driven
|\
| * a0e9bfdf6a (retronym/topic/disable-tag-driven) Disable tag driven release of the distribution
|/
*   7b4579776d Merge pull request #5978 from retronym/review/5967
|\
| * c791df1727 (retronym/review/5967) Avoid calls to static initializers in runtime reflection
* |   c48b1bc433 Merge pull request #5782 from retronym/ticket/10233
|\ \
| * | 632c2abc50 (retronym/ticket/10233) Expand test case to consider local modules
| * | 92b1cc3875 Improve serializability of lambdas that call methods in module
|  /
* |   585f515cc0 Merge pull request #5792 from lrytz/t7936
|\ \
| * | 5a25c2a6e3 Don't minimize reduntant parents used in super calls
| * | f18b249405 Fix access to protected members in package-protected classes
| * | 92f4e1ef61 Fix bug in minimizeParents, keep all java interfaces
| |/
* |   7b25464819 Merge pull request #5787 from som-snytt/issue/10240
|\ \
| * | 61f382702a SI-10240 Additional scouting
| * | 8a4b2ce154 SI-10240 Better pos for infix type arg
|  /
* |   4227645888 Merge pull request #5916 from eed3si9n/wip/repl
|\ \
| * | a252aa6f33 (retronym/review/5916) Improve help message for :kind in the REPL
| * | d465df421e Clean up :kind's error message per review
| * | 74850c881d Update REPL's :help text for :kind
| * | c3af1fcf7d Implement :kind handling for type lambdas
| * | 325c7c14fe Improve :kind by only accepting type expressions
|  /
* |   96d06cd7c3 Merge pull request #5798 from milessabin/topic/issue-ambiguous-context
|\ \
| * | 9eb8d416c9 Use the correct Context.
|  /
* |   6c1be058a1 Merge pull request #5971 from ruippeixotog/issue/10398
|\ \
| * | f1fdc1901c Prevent `inferImplicitValue` from reporting false divergent implicits
* | |   17ef5ad0a3 Merge pull request #5956 from retronym/faster/findClass
|\ \ \
| * | | bd7341754f (retronym/faster/findClass) A bit of doc comments for our ClassPath implementation
| * | | b9520211b2 Optimize Classpath.findClass
* | | |   c331c7831b Merge pull request #5976 from lrytz/sd402
|\ \ \ \
| * | | | 7c107ee6e8 Add missing phase travel when searching a companion in the backend
| | |_|/
| |/| |
* | | |   ddf4e2c86c Merge pull request #5972 from joymufeng/2.12.x
|\ \ \ \
| * | | | 34d2f332d4 Constructing a mutable BitSet with an empty array will return an empty instance. Fixes scala/bug#10399
| | |/ /
| |/| |
* | | |   01307fab3d Merge pull request #5974 from som-snytt/issue/10402
|\ \ \ \
| |_|/ /
|/| | |
| * | | 6969b1da94 Don't checkUnused java units
|/ / /
* | |   e6bfbca861 Merge pull request #5970 from som-snytt/issue/2133-3160-3836-imports
|\ \ \
| * | | 56b6845c17 Spec relaxed import, review
| * | | b878bc5286 Spec relaxed import behavior
* | | |   3b4f3293e4 Merge pull request #5727 from som-snytt/issue/10120-communal-proof
|\ \ \ \
| * | | | a51b9865f5 SI-10120 ReplReporter handles message indent
| * | | | 79eeec3c9a SI-10120 Extra advice on unclosed char literal
| * | | | 2e80fb680d SI-10133 Deprecate unescaped single quote char lit
| |/ / /
* | | |   ae9b465f3d Merge pull request #5848 from rorygraves/2.12.x_profile2
|\ \ \ \
| * | | | e929236a4b Add support for phase profiling generating inforamtion per phase:   - Wall Clock Time (ms) - wall clock time   - Idle Time (ms) - time blocked   - cpu time (ms) - reported cpu time   - user time (ms) - reported user time   - allocated (mb) - bytes allocated during phase   - retainedHeap (mb) - retained heap after phase (enable GC for more accurate counts)   - gcTime (ms) - time spent in GC.
|  / / /
* | | |   343a19949c Merge pull request #5964 from lrytz/inline-from
|\ \ \ \
| * | | | dddf5a2a41 Use MultiStringSetting for -opt-inline-from
| * | | | 0c515344a5 Tests for compilation with various -opt-inline-from settings
| * | | | be5126fcf1 Extensive help text for -opt-inline-from
| * | | | 7230580162 Add -opt:l:inline and -opt-inline-from, deprecate -opt:l:classpath
| * | | | 1cebf8fafd parser and checker for -opt-inline-from setting
|  / / /
* | | |   65980ea578 Merge pull request #5968 from Jasper-M/topic/t5355
|\ \ \ \
| |_|/ /
|/| | |
| * | | 6a3ec51b17 Fix 5355: wrong error message for cyclic structural types
|  / /
* | |   a6e713499d Merge pull request #5966 from retronym/topic/checkinit-regression
|\ \ \
| |_|/
|/| |
| * | f963b53a92 (retronym/topic/checkinit-regression) Fix regression under -Xcheckinit: param accessors don't need init checking
| |/
* |   a35c3c952c Merge pull request #5965 from dragos/issue/stability-case-class
|\ \
| * | 79723d0243 Test case for scala/bug#10343
| * | bd0a609136 Keep default getters next to the original definition
* | |   c8d84ef277 Merge pull request #5799 from haveo/si-9967-2.12
|\ \ \
| * | | c6ed9537f2 Fix externally linked scaladoc in 2.12
|  / /
* | |   8bdc2b2012 Merge pull request #5833 from rorygraves/2.12.x_minor_opts
|\ \ \
| * | | 0e2bed17ff minor BTypes optimisations
|  / /
* | |   7f136819af Merge pull request #5944 from lrytz/t10290
|\ \ \
| * | | 6c48f32f2d Fix code gen for Outer.super[Q].foo
|  / /
* | |   809ec11112 Merge pull request #5919 from som-snytt/issue/under-is-lower
|\ \ \
| |_|/
|/| |
| * | a853608f02 Underscore is lower case
|  /
* |   0a01e0be99 Merge pull request #5960 from lrytz/t10389
|\ \
| * | 8291928286 User-defined case companion apply: unlink default getters
|  /
* |   4da24f8ff7 Merge pull request #5796 from Jasper-M/fix/negative-duration
|\ \
| * | 2a2f588ea8 Fix rounding errors in creation of Durations. Use round instead of manually trying to convert to a Long.
|  /
* |   0c3e73b5ea Merge pull request #5896 from milessabin/topic/conditionalize-travis-build
|\ \
| |/
|/|
| * c08cabefb4 Split Travis publishing out to external script and simplify logic.
| * a957b6fda5 Don't attempt to publish if there's no private key.
*   64870a900a Merge pull request #5921 from janekdb/2.12/intellij-code-analysis-new-modifier-compiler
|\
| * 71e76e8c05 Remove new modifier on case classes in compiler
*   5956a026d0 Merge pull request #5932 from janekdb/topic/2.12/intellij-code-analysis-unnecessary-semicolon
|\
| * 83b5051518 Remove unnecessary semicolons
*   3a4ac96a8c Merge pull request #5943 from janekdb/topic/2.12/intellij-code-analysis-orNull
|\
| * 8bb4ed6e7b Prefer orNull library method
*   c84ea81e5c Merge pull request #5947 from estsauver/10369
|\
| * d38d754519 Support serializable on MatchError
*   af353e06cc Merge pull request #5948 from janekdb/topic/2.12/scaladoc-fix-1
|\
| * d372178496 Fix missing Scaladoc markdown
*   76b492f181 Merge pull request #5953 from Atry/patch-9
|\
| * 80d0a91ad2 Add icon for alias
*   a610630f05 Merge pull request #5925 from lrytz/t10180
|\
| * 5d5511d436 Review feedback, some performance-related cleanups
| * e5ea3abfa3 Parse signatures when collecting referenced nested classes
| * e3bee06712 Don't emit generic signatures for types erasing to a primitive
| * ddf3b92d9b Test for java inner class referenced in signature only
| * 390ab4a7e8 Fix generic signatures for classes nested in modules
| * cc1f62d4f1 Move ClassNode traverser for collecting nested classes
*   c4a732edab Merge pull request #5959 from lrytz/nullNothingScalaSig
|\
| * 259824e752 [nomerge] Scala classes ending in `$` get a signature
*   65486a8423 Merge pull request #5927 from retronym/ticket/10353
|\
| * 0c10149829 (retronym/ticket/10353) Fix completion of x.bar.<TAB>, where bar takes dependent implicits
* 80bfdee470 Merge pull request #5929 from retronym/ticket/9716
* 3cc2360b5e (retronym/ticket/9716) Improve presentation compiler with Shapeless macros

$ git merge 65486a8423
Auto-merging test/junit/scala/tools/nsc/interpreter/CompletionTest.scala
CONFLICT (content): Merge conflict in test/junit/scala/tools/nsc/interpreter/CompletionTest.scala
Automatic merge failed; fix conflicts and then commit the result.

# minor conflicts due to https://github.com/scala/scala/pull/5903

$ git commit
[merge/2.12.x-to-2.13.x-20170717 de87b91e46] Merge commit '65486a8423' into merge/2.12.x-to-2.13.x-20170717

$ git merge c4a732edab -s ours
Merge made by the 'ours' strategy.

$ git merge ae9b465f3d

# minor conflicts

$ git commit
[merge/2.12.x-to-2.13.x-20170717 6e23bd3752] Merge commit 'ae9b465f3d' into merge/2.12.x-to-2.13.x-20170717

$ git merge 79eeec3c9a

# part of https://github.com/scala/scala/pull/5727

$ git merge a51b9865f5 -s ours
Merge made by the 'ours' strategy.

# part of https://github.com/scala/scala/pull/5727, already present in 2.13.x according to https://github.com/scala/scala/pull/5727#issuecomment-312918942

$ git merge scala/2.12.x

# conflicts due to REPL refactoring in 2.13.x

$ git commit
[merge/2.12.x-to-2.13.x-20170717 c162d40813] Merge remote-tracking branch 'scala/2.12.x' into merge/2.12.x-to-2.13.x-20170717
```

### CODE REVIEW

**Comment by szeiger** [comment]
Oops, I guess I should have added `[ci: last-only]`. This will keep our server farm busy for a while...

**Comment by lrytz** [comment]
Actually, you're (un)lucky: there's a long-standing limitation in scabooo that it doesn't build commits that don't fit on the first page of 100 (https://github.com/scala/scala-dev/issues/279), so there were no builds running here. I started one for the last commit manually by setting the right parameters https://scala-ci.typesafe.com/job/scala-2.12.x-validate-main/6221/parameters/

**Review by lrytz — APPROVED** [review]

**Comment by szeiger** [comment]
Test failure in run/repl-kind.scala:

```
!! 1 - run/repl-kind.scala                       [output differs]
##### Log file '/Users/szeiger/code/scala/test/files/run/repl-kind-run.log' from failed test #####


scala> :kind Int
scala.Int's kind is A

scala> :kind scala.Option
scala.Option's kind is F[+A]

scala> :k (Int, Int) => Int
scala.Function2's kind is F[-A1,-A2,+A3]

scala> :k -v Either
scala.util.Either's kind is F[+A1,+A2]
* -(+)-> * -(+)-> *
This is a type constructor: a 1st-order-kinded type.

scala> :k -v scala.collection.generic.ImmutableSortedMapFactory
scala.collection.generic.ImmutableSortedMapFactory's kind is X[CC[A,B] <: scala.collection.immutable.SortedMap[A,B] with scala.collection.SortedMapLike[A,B,CC[A,B]]]
(* -> * -> *(scala.collection.immutable.SortedMap[A,B] with scala.collection.SortedMapLike[A,B,CC[A,B]])) -> *
This is a type constructor that takes type constructor(s): a higher-kinded type.

scala> :kind -v Predef.Pair
              ^
       error: value Pair is not a member of object Predef


scala> :kind -v Predef.Pair[Int, Int]
              ^
       error: value Pair is not a member of object Predef


scala> trait Functor[F[_]] {}
defined trait Functor

scala> :kind -v Functor
Functor's kind is X[F[A]]
(* -> *) -> *
This is a type constructor that takes type constructor(s): a higher-kinded type.

scala> object Bar { class Bop }
defined object Bar

scala> import Bar.Bop
import Bar.Bop

scala> :kind Bop
Bar.Bop's kind is A

scala> type IntTuple[+A] = (Int, A)
defined type alias IntTuple

scala> :kind IntTuple
scala.Tuple2's kind is F[+A1,+A2]

scala> :kind ({type l[A] = Either[Int, A]})#l
scala.util.Either's kind is F[+A1,+A2]

scala> trait Nat[-F1[_], +F2[_]] {}
defined trait Nat

scala> type ~>[-F1[_], +F2[_]] = Nat[F1, F2]
defined type alias $tilde$greater

scala> :kind ({type l[F[-_]] = F ~> List})#l
Nat's kind is X[-F1[A1],+F2[A2]]

scala> :kind 5
scala.Int's kind is A

scala> :kind Nonexisting
       ^
       error: not found: value Nonexisting
```

This test was introduced in #5916 and interacts with the other REPL changes in 2.13.x. @eed3si9n Can you take a look if there are any regressions here or if the changes in the output are expected in 2.13?

**Comment by dwijnand** [comment]
There are definite regressions there:

```
scala> :k (Int, Int) => Int
scala.Function2's kind is F[-A1,-A2,+A3]

...

scala> :kind ({type l[A] = Either[Int, A]})#l
scala.util.Either's kind is F[+A1,+A2]
```

The check file is right, it should continue to read:

```
scala> :k (Int, Int) => Int
(Int, Int) => Int's kind is A

...

scala> :kind ({type l[A] = Either[Int, A]})#l
scala.util.Either[Int,?]'s kind is F[+A]
```

**Comment by szeiger** [comment]
I updated the last merge commit with changes from https://github.com/scala/scala/pull/5916/files#diff-9a0a4f1d0ad315e65b7c15cbad888efa which are now in IMain

**Comment by SethTisue** [comment]
let's see how 2.13.x-release-main goes: https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-release-main/289/

**Comment by lrytz** [comment]
Good, except for the community build

```
[info] Project monix-------------------: FAILED (RuntimeException: )
```

**Comment by lrytz** [comment]
should be an easy fix

```
[monix] [error] scala/monix/execution/atomic/BoxedLong.scala:26: object creation impossible, since method parseString in trait Numeric of type (str: String)Option[monix.execution.atomic.BoxedLong] is not defined
[monix] [error]   implicit val numeric = new Numeric[BoxedLong] {
[monix] [error]                              ^
[monix] [error] one error found
```

**Comment by lrytz** [comment]
Ah, seth is tracking this at https://github.com/scala/community-builds/issues/572
