### PR TITLE
Fix typo in JavaConverters doc

### PR DESCRIPTION
**Pull request by ashawley**
There is no such thing as scala.collection.mutable.concurrent.Map

    error: object concurrent is not a member of package scala.collection.mutable

Introduced in 2908236a.  Found by @cescude

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]

**Comment by SethTisue** [comment]
good catch, thanks!
