### PR TITLE
any2stringadd is ineligible under -Xsource:3-cross

### LINKED ISSUE #13004: Compiler doesn't search implicit scope for + operator with -Xsource:3 enabled
## Reproduction steps

Scala version: 2.13.14 with -Xsource:3 enabled

```scala
scala>   case class Money(value: Double)
     |   object Money {
     |     implicit class MoneySyntax(private val self: Money)  extends AnyVal {
     |       def +(other: Money): Money = Money(self.value + other.value)
     |     }
     |   }
     |
class Money
object Money

scala> Money(1) + Money(2)
                       ^
       error: type mismatch;
        found   : Money
        required: String
            ^
       error: Converting to String for concatenation is not supported in Scala 3 (or with -Xsource-features:any2stringadd).
       Scala 3 migration messages are issued as errors under -Xsource:3. Use -Wconf or @nowarn to demote them to warnings or suppress.
       Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=scala3-migration, site=scala.Predef.any2stringadd
```

## Problem

This example compiles perfectly using Scala 2.13.12 with -Xsource:3 enabled. Starting with 2.13.13 it fails with error above.  Adding -Xsource-features:any2stringadd doesn't help - it just fails with `value + is not a member of Money` error.  Renaming `+` to any other identifier fixes the issue.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#13004

`-Xsource-features:any2stringadd` correctly suppresses the conversion without breaking inference where it would otherwise apply.

### CODE REVIEW

**Comment by som-snytt** [comment]
This restores a kind of "special case" for the conversion, but there is already a spot for adding such special cases.

First try was in typer, when you see `any2stringadd`, run `inferView` again, but with a starting context constructed to shadow `any2stringadd`. (That was to avoid a special case lower down the stack.) I didn't get that to work right away, and by the time I looked at the shadowing in `ImplicitComputation`, decided to save that for a rainier day next rainy season. There a couple of open tickets in this area; and `ImplicitInfo` now tracks its `ImportInfo`, so maybe shadowing can be made more correct.

**Comment by som-snytt** [comment]
Also worth noting that primitive `+(String)` is just a deprecation.

Oh, ha, for ordinary warning, you don't see the verbose message telling you how to configure it. (`-Wconf:any:wv`)

```
scala '-Wconf:cat=deprecation&origin=scala.(Int|Double|Float|Long|Short|Char|Byte).+:e'
```

TIL it's only on numerics and is not in the spec.

**Comment by lrytz** [comment]
I must be missing something. Is it expected that this doesn't compile with plain 2.13?

```scala
class Plusser {
  def + (o: Int) = o
  def p (o: Int) = o
}
class C
object C { implicit def tuplu(c: C): Plusser = new Plusser }

class Test {
  val c = new C()
  def t = c + 1  // type mismatch, found: Int, required: String
  def u = c p 1  // ok
}
```

It works with Scala 3.

**Comment by som-snytt** [comment]
I am totally nonplussed.

edit: oh, this is just that the conversion in lexical scope is used, so the conversion in implicit scope is not. I would have to consult the law books on Scala 3.

**Comment by som-snytt** [comment]
So that's cool, but why not just fix the root import like dotty? Normally I love mucking with root imports.

https://github.com/scala/scala3/pull/7164

That aligns with dotty, which does not quash the conversion but just doesn't import it by default.

**Review by lrytz — APPROVED** [review]
👍  nice
