### PR TITLE
Scala 3.3.1-RC1 (enable TastyTest on JDK 21)

### PR DESCRIPTION
**Pull request by SethTisue**
this should work on JDK 21 now that lampepfl/dotty#17536 has been merged?

### CODE REVIEW

**Comment by SethTisue** [comment]
@bishabosha this fails (not just on JDK 21) with:

```diff
ERROR: /Users/tisue/scala.213/test/tasty/neg/src-2/TestSaferExceptions_fail.scala failed, unexpected output.
--- check
+++ output
@@ -1,2 +1,2 @@
-TestSaferExceptions_fail.scala:5: error: Unsupported Scala 3 erased context function type in bounds of type mayThrow: erased tastytest.SaferExceptions.CanThrowCapability[E] ?=> A; found in object tastytest.SaferExceptions.
+TestSaferExceptions_fail.scala:5: error: Unsupported Scala 3 erased value x$1; found in method apply in  tastytest.SaferExceptions.<refinement>.
   def test = SaferExceptions.safeDiv(1, 0) // error
ERROR: /Users/tisue/scala.213/test/tasty/neg/src-2/TestErasedTypes_fail.scala failed, unexpected output.
--- check
+++ output
@@ -1,7 +1,1 @@
-TestErasedTypes_fail.scala:6: error: Unsupported Scala 3 erased modifier in refinement of type F; found in class tastytest.ErasedTypes.Bar.
-  def test1 = new Bar[Foo]
-                  ^
-TestErasedTypes_fail.scala:7: error: Unsupported Scala 3 erased modifier in refinement of type F; found in class tastytest.ErasedTypes.Baz.
-  def test2 = new Baz[Foo]
-                  ^
 TestErasedTypes_fail.scala:9: error: Unsupported Scala 3 erased value x; found in method foo1 in trait tastytest.ErasedTypes.Foo.
@@ -15,2 +9,2 @@
                                    ^
-5 errors
+3 errors
```

can you explain what's going here? is this a concern for the 2.13.11 release? (ideally the 2.13.11 TASTy reader would work with any 3.3.x release, not just 3.3.0 specifically?)

is this actually a progression, by any chance? an expected-to-fail test that doesn't fail as much anymore and that's actually good?

provisionally marking as "prio:blocker", at least until we understand it better

**Comment by bishabosha** [comment]
The encoding of erased parameters changed in 3.3.x since I first did the tasty port I guess?

So yeah the test is expected to fail, now it fails with a different message, but still expected. This error shouldn't be so common as erased is an experimental feature anyway - updating the check file should be all that's needed (`/test/tasty/neg/src-2/TestSaferExceptions.check`)

I guess someone could attempt to make a prettier error message than `found in method apply in  tastytest.SaferExceptions.<refinement>`.

Also the error message could be updated to suggest the project maintainer update the check file (and print its path)
