### PR TITLE
[#11159][do not merge] Prototype proposal to fix seqview and indexedSeqView operators

### LINKED ISSUE #11159: Regression: prepended SeqView should still be a SeqView
`1 +: 2 +: Nil.view` compiles in Scala 2.12:
```
Welcome to Scala 2.12.6 (GraalVM 1.0.0-rc2, Java 1.8.0_171).
Type in expressions for evaluation. Or try :help.

scala> 1 +: 2 +: Nil.view
res0: scala.collection.SeqView[Int,Seq[_]] = SeqViewAA(...)
```

but not in Scala 2.13.0-M5

```
Welcome to Scala 2.13.0-M5 (GraalVM 1.0.0-rc2, Java 1.8.0_171).
Type in expressions for evaluation. Or try :help.

scala> 1 +: 2 +: Nil.view
         ^
       error: value +: is not a member of scala.collection.View[Int]
```

### PR DESCRIPTION
**Pull request by joshlemer**
This is a prototype / strawman proposal to fix scala/bug#11159 

Is it okay to move the various ```@`inline` final def``` symbolic aliases into the `Collection` proper trait, rather than the `CollectionOps` trait? This would allow Views, SeqViews, and IndexedSeqViews to override the now-non-final symbolic operators in SeqOps.

Proof of the api are found in the junit tests, [here](https://github.com/scala/scala/pull/7286/files#diff-c236299738fe3a89e2b020e973942a02R8) and [here](https://github.com/scala/scala/pull/7286/files#diff-5ed8925325b54af8398af95187549155R9)

### CODE REVIEW

File: src/library/scala/collection/Iterable.scala [hunk 1]
```diff
@@ -705,7 +705,7 @@ trait IterableOps[+A, +CC[_], +C] extends Any with IterableOnce[A] with Iterable
   })
 
   /** Alias for `concat` */
-  @`inline` final def ++ [B >: A](suffix: IterableOnce[B]): CC[B] = concat(suffix)
+  def ++ [B >: A](suffix: IterableOnce[B]): CC[B] = concat(suffix)
```
Comment (julienrf) [inline src/library/scala/collection/Iterable.scala:708]: I think we should at least have a `@deprecatedOverriding` annotation explaining that this method must be an alias to `concat`, and that `concat` is usually the method you want to override.

**Review by julienrf — COMMENTED** [review]
> Is it okay to move the various ```@`inline` final def``` symbolic aliases into the `Collection` proper trait, rather than the `CollectionOps` trait? This would allow Views, SeqViews, and IndexedSeqViews to override the now-non-final symbolic operators in SeqOps.

I think we should still document or even emit a warning if users try to override the symbolic aliases instead of overriding the implementation method. Maybe emitting a warning is enough, btw (ie we don’t need to do the final overrides in the non-`Ops` traits).

Overall, I’m a bit worried by the complexity added by all these forwarder methods and overloads. Although I agree that scala/bug#11159 is an important problem to fix…

**Comment by szeiger** [comment]
I agree that the complexity is too high for what appears to be a relatively minor problem. Unfortunately, a good solution (in the form of transparent methods or whatever replacement finds its way into Scala 3.0) will still have to wait for a while.

**Comment by adriaanm** [comment]
Based on Stefan's feedback, I'm going to close this one. Happy to reopen or consider an alternative fix, of course!
