### PR TITLE
Optimize `List()` to `Nil` again (fixing 2.13.4 regression)

### LINKED ISSUE #12548: `Nil` rewrite still broken on 2.13
## Reproduction steps

```scala
class C {
  def f: List[Int] = List()
}
```

## Problem

2.12
```
[[syntax trees at end of                     typer]] // lister.scala
package <empty> {
  class C extends scala.AnyRef {
    def <init>(): C = {
      C.super.<init>();
      ()
    };
    def f: List[Int] = scala.collection.immutable.Nil
  }
}
```
2.13
```
[[syntax trees at end of                     typer]] // lister.scala
package <empty> {
  class C extends scala.AnyRef {
    def <init>(): C = {
      C.super.<init>();
      ()
    };
    def f: List[Int] = scala.`package`.List.apply[Nothing]()
  }
}

[[syntax trees at end of              constructors]] // lister.scala
package <empty> {
  class C extends Object {
    def f(): List = scala.`package`.List().apply(scala.collection.immutable.Nil).$asInstanceOf[List]();
    def <init>(): C = {
      C.super.<init>();
      ()
    }
  }
}
```

### LINKED ISSUE #12549: -Ygen-asmp has a funny way of saying output dir does not exist
## Reproduction steps

2.13.8

```scala
> scalac -Ygen-asmp /tmp/test-asmp foo.scala    # forgot to create output dir
error: java.lang.IllegalStateException: don't know how to handle an output of /tmp/test-asmp [class scala.reflect.io.PlainNioFile]
        at scala.tools.nsc.backend.jvm.ClassfileWriters$FileWriter$.apply(ClassfileWriters.scala:185)
        at scala.tools.nsc.backend.jvm.ClassfileWriters$ClassfileWriter$.$anonfun$apply$7(ClassfileWriters.scala:89)
        at scala.tools.nsc.backend.jvm.ClassfileWriters$ClassfileWriter$.apply(ClassfileWriters.scala:89)
        at scala.tools.nsc.backend.jvm.PostProcessor.initialize(PostProcessor.scala:57)
        at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.initialize(GenBCode.scala:96)
        at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.$anonfun$run$1(GenBCode.scala:79)
        at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.run(GenBCode.scala:78)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1524)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1508)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1500)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1634)
        at scala.tools.nsc.Driver.doCompile(Driver.scala:48)
        at scala.tools.nsc.MainClass.doCompile(Main.scala:30)
        at scala.tools.nsc.Driver.process(Driver.scala:68)
        at scala.tools.nsc.Driver.main(Driver.scala:82)
        at scala.tools.nsc.Main.main(Main.scala)
```

## Problem

I expected a nice error message with help text.

### PR DESCRIPTION
**Pull request by som-snytt**
Special dealiasing of `scala.List` (once needed by patmat) was removed in 2.13.4, but detection of `List()` for rewrite to `Nil` relied on it and has been broken.

The check for empty `List.apply` now handles `scala.List` and could be made to dealias more generally, see the test, but that is disabled for now as overly liberal.

Also improve error handling if my outputdir for `-Ygen-asmp` doesn't exist. Notice that the setting is not `OutputDir` because that is hardcoded to `-d` only.

Fixes scala/bug#12548
Fixes scala/bug#12549

### CODE REVIEW

File: test/files/neg/compile-time-only-a.check [hunk 1]
```diff
@@ -64,9 +64,6 @@ compile-time-only-a.scala:60: error: C7
 compile-time-only-a.scala:61: error: C7
   val c707a: List[C7] = ???
              ^
-compile-time-only-a.scala:62: error: C7
-  val c707b = List[C7]()
-                   ^
```
Comment (lrytz) [inline test/files/neg/compile-time-only-a.check:69]: could be worth updating the test, commenting why no error is issued here, and maybe add a variant that's not eliminated by magic.

**Review by lrytz — APPROVED** [review]
Thanks!

**Comment by SethTisue** [comment]
@som-snytt have you looked at the non-empty case recently...?

it seems from https://github.com/scala/scala/pull/6994 that small lists are also supposed to get optimized, but I'm not seeing that happening in the latest 2.13.9 nightly. it works in 2.12.x:

```
scala 2.12.16-bin-e9e4ebb> class C { def foo = List("foo") }
defined class C

scala 2.12.16-bin-e9e4ebb> :javap C#foo
...
         4: ldc           #19                 // String foo
         6: getstatic     #25                 // Field scala/collection/immutable/Nil$.MODULE$:Lscala/collection/immutable/Nil$;
         9: invokespecial #29                 // Method scala/collection/immutable/$colon$colon."<init>":(Ljava/lang/Object;Lscala/collection/immutable/List;)V
        12: areturn
...
```

but in 2.13.x:

```
...
        21: invokevirtual #41                 // Method scala/runtime/ScalaRunTime$.wrapRefArray:([Ljava/lang/Object;)Lscala/collection/immutable/ArraySeq;
        24: invokevirtual #47                 // Method scala/collection/immutable/List$.apply:(Lscala/collection/immutable/Seq;)Ljava/lang/Object;
...
```

would digging into this interest you?

this came up on Discord today in #scala-users

**Comment by som-snytt** [comment]
@SethTisue thanks, I missed that discussion and will take a look.

**Comment by som-snytt** [comment]
@SethTisue yes it uses the same test. (I wonder why `Seq()` is not rewritten.) `-Vprint:cleanup` on the test shows a lot of colons.
```
    def main(args: Array[String]): Unit = {
      val myList: List = new collection.immutable.::(Test.this.next(), new collection.immutable.::(Test.this.next(), new collection.immutable.::(Test.this.next(), scala.collection.immutable.Nil))).$asInstanceOf[List]();
      scala.Predef.assert(myList.==(new collection.immutable.::("1", new collection.immutable.::("2", new collection.immutable.::("3", scala.collection.immutable.Nil)))), {
        (() => Test.this.$anonfun$main$1(myList))
      })
    };
```
Jason comments that he fixed the test because it only works for reference types.

https://github.com/scala/scala/pull/6994#issuecomment-413379074

With that Aussie inscrutability, he doesn't explain why. Maybe because the use cases for small lists of ints are served by range or iterator. Really I'd want unboxed. I wonder if people using floats just have them in an array.

I checked that it works for only one element
```
iw.this.res2 = new collection.immutable.::("a", scala.collection.immutable.Nil).$asInstanceOf[List]();
```

I don't see a versioned prompt, so I don't believe you when you claim to be using a recent HEAD. Maybe you're using one of those new-fangled CLI tools that doesn't quite work yet.

**Comment by som-snytt** [comment]
While in cleanup to understand boxing, or deboxing, I noticed that the `Seq()` rewrite was intended but apparently did not survive the forward merge. I'll chase that down.
