### PR TITLE
Make scala.math compile under Dotty

### PR DESCRIPTION
**Pull request by odersky**
Need to change unrelated inner classes so that they
have different names. Dotty does not allow a type
"not-overriding" a class with same name in a basetype.

### CODE REVIEW

**Comment by soc** [comment]
@odersky Shall we add a similar change to scalac, too?
Is the subtyping relationship assumed implicitly if names match, or does/should it require an explicit `extends` clause?

**Comment by retronym** [comment]
We'll need to bootstrap a new version of scalacheck with this change:

```
Caused by: java.lang.NoSuchMethodError: scala.math.Numeric.mkNumericOps(Ljava/lang/Object;)Lscala/math/Numeric$Ops;
    at org.scalacheck.Gen$.chooseNum(Gen.scala:611)
    at org.scalacheck.Arbitrary$.org$scalacheck$Arbitrary$$$anonfun$3(Arbitrary.scala:85)
    at org.scalacheck.Arbitrary$$$Lambda$8859/360520900.apply(Unknown Source)
```

An alternative might be to define `mkNumericOps(Ljava/lang/Object;)Lscala/math/Numeric$Ops` in a parent trait of `object Numeric` to get a bridge method.

/cc @adriaanm

**Comment by adriaanm** [comment]
+1 on adding a transitory method

**Comment by adriaanm** [comment]
Given the binary compatibility concerns, we'll probably have to settle for deprecating in 2.12 and reworking in 2.13.
