### PR TITLE
deprecates macro def return type inference

### PR DESCRIPTION
**Pull request by xeno-by**
With the new focus on quasiquotes in macro implementations, we now have
to change the way how inference of macro def return types works.

Previously, if the return type of a macro def wasn’t specified, we looked into
the signature of its macro impl, took its return type (which could only
be c.Expr[T]) and then assigned T to be the return type of the macro def.

We also had a convenient special case which inferred Any in case when
the body of the macro impl wasn’t an expr. That avoided reporting spurious
errors if the macro impl had its body typed incorrectly (because in that
case we would report a def/impl signature mismatch anyway) and also provided
a convenience by letting macro impls end with `???`.

However now we also allow macro impls to return c.Tree, which means that
we are no longer able to do any meaningful type inference, because c.Tree
could correspond to tree of any type.

Unfortunately, when coupled with the type inference special case described
above, this means that the users who migrate from exprs to quasiquotes
are going to face an unpleasant surprise. If they haven’t provided
explicit return types for their macro defs, those types are going to be
silently inferred as `Any`!

This commit plugs this loophole by prohibiting type inference from
non-expr return types of macro impls (not counting Nothing). Moreover,
it also deprecates c.Expr[T] => T inference in order to avoid confusion
when switching between exprs and quasiquotes.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by xeno-by** [comment]
scala-internals topic: https://groups.google.com/forum/#!topic/scala-internals/GubDJHoalTo

**Comment by milessabin** [comment]
What's up with this PR? In the queue for the last two days?

**Comment by retronym** [comment]
I liked the sounds of this from the commit message, and the contents are just as good.

LGTM.

**Comment by retronym** [comment]
I wonder why we're not seeing this [build failure](https://scala-webapps.epfl.ch/jenkins/job/pr-scala-test/4092/console) reported here:

```
fail - neg/macro-invalidret  [output differs]% scalac macro-invalidret/Impls_1.scala
% scalac macro-invalidret/Macros_Test_2.scala
Macros_Test_2.scala:2: error: macro implementation has incompatible shape:
 required: (c: scala.reflect.macros.BlackboxContext): c.Expr[Any]
 or      : (c: scala.reflect.macros.BlackboxContext): c.Tree
 found   : (c: scala.reflect.macros.BlackboxContext): Int
type mismatch for return type: Int does not conform to c.Expr[Any]
  def foo1 = macro Impls.foo1
                         ^
Macros_Test_2.scala:3: error: macro implementation has incompatible shape:
 required: (c: scala.reflect.macros.BlackboxContext): c.Expr[Any]
 or      : (c: scala.reflect.macros.BlackboxContext): c.Tree
 found   : (c: scala.reflect.macros.BlackboxContext): reflect.runtime.universe.Literal
type mismatch for return type: reflect.runtime.universe.Literal does not conform to c.Expr[Any]
  def foo2 = macro Impls.foo2
                         ^
Macros_Test_2.scala:6: error: macro defs must have explicitly specified return types
  def foo5 = macro Impls.foo5
      ^
Macros_Test_2.scala:14: error: exception during macro expansion:
scala.NotImplementedError: an implementation is missing
    at scala.Predef$.$qmark$qmark$qmark(Predef.scala:227)
    at Impls$.foo3(Impls_1.scala:7)

  foo3
  ^
Macros_Test_2.scala:15: error: macro implementation is missing
  foo4
  ^
Macros_Test_2.scala:17: warning: a pure expression does nothing in statement position; you may be omitting necessary parentheses
  foo6
  ^
one warning found
5 errors found

% diff /localhome/jenkins/c/workspace/pr-scala-test/scala/test/files/neg/macro-invalidret-neg.log /localhome/jenkins/c/workspace/pr-scala-test/scala/test/files/neg/macro-invalidret.check
@@ -15,6 +15,9 @@ type mismatch for return type: reflect.runtime.universe.Literal does not conform
 Macros_Test_2.scala:6: error: macro defs must have explicitly specified return types
   def foo5 = macro Impls.foo5
       ^
+Macros_Test_2.scala:7: warning: macro defs must have explicitly specified return types (inference of Int from macro impl's c.Expr[Int] is deprecated and is going to stop working in 2.12)
+  def foo6 = macro Impls.foo6
+      ^
 Macros_Test_2.scala:14: error: exception during macro expansion:
 scala.NotImplementedError: an implementation is missing
    at scala.Predef$.$qmark$qmark$qmark(Predef.scala:227)
@@ -28,5 +31,5 @@ Macros_Test_2.scala:15: error: macro implementation is missing
 Macros_Test_2.scala:17: warning: a pure expression does nothing in statement position; you may be omitting necessary parentheses
   foo6
   ^
-one warning found
+two warnings found
 5 errors found

```

**Comment by xeno-by** [comment]
@retronym That's a good question. Btw does it fail for you as well? Because for me it does not.

**Comment by xeno-by** [comment]
@retronym Oh boy looks like there's a bug in my partest-wrapping scripts. Never occurred before, sorry, will fix.

**Comment by xeno-by** [comment]
@retronym Fixed. My per-repository scalac flags have been inadvertently leaking into SCALAC_OPTS. This particular problem was caused by `-deprecation` being applied to the test even though it wasn't specified in the flags file. I just added this flag, and now everything should work.
