### PR TITLE
TASTy reader: add support for Scala 3.0.0-M3

### LINKED ISSUE #12259: Erasure of tasty method with ValueOf[Int with Singleton] param
a method with a parameter of type `ValueOf[I]` where `I <: Int` will erase to `java.lang.Integer` and not `java.lang.Object` as the descriptor of `Values.reify` requires
## reproduction steps

using Scala (2.13.4),

```scala
// compile with Scala 3.0.0-M2
object Values {
  def reify[I <: Int](implicit I: ValueOf[I]): I = valueOf[I]
}
```

```scala
// compile with Scala 2.13.4
object Test extends App {
  println(Values.reify[3])
}
```

## problem

runtime error:
```scala
[error] Test scala.tools.tastytest.TastyTestJUnit.run failed: java.lang.NoSuchMethodError: tastytest.Values$.reify(Ljava/lang/Integer;)I, took 18.115 sec
[error]     at tastytest.TestValues$.$anonfun$new$1(TestValues.scala:8)
[error]     at tastytest.Suite.$anonfun$runImpl$2(Suite.scala:49)
[error]     at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error]     at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error]     at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
[error]     at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:889)
[error]     at tastytest.Suite.runImpl(Suite.scala:48)
[error]     at tastytest.Suite.main(Suite.scala:40)
[error]     at tastytest.TestValues.main(TestValues.scala)
```

### LINKED ISSUE #12286: Tasty: Support Scala 3.0.0-M3
- [ ] Erase `scala.Matchable` to Object
- [ ] ignore `EXPORT` TASTy tag

### PR DESCRIPTION
**Pull request by bishabosha**
This PR does the minimal thing and substitutes references to `scala.Matchable` to `scala.Any`,

there was no need to add an extra test case for Export clauses in tasty - they were already tested.

Also adds test cases for the updates to trait encoding and Value class erasure in Scala 3

fixes https://github.com/scala/bug/issues/12259
fixes https://github.com/scala/bug/issues/12286

### CODE REVIEW

File: project/DottySupport.scala [hunk 1]
```diff
@@ -12,8 +12,8 @@ import sbt.librarymanagement.{
   * Settings to support validation of TastyUnpickler against the release of dotty with the matching TASTy version
   */
 object TastySupport {
-  val supportedTASTyRelease = "3.0.0-M2" // TASTy version 25.1
-  val scala3Compiler = "org.scala-lang" % "scala3-compiler_3.0.0-M2" % supportedTASTyRelease
+  val supportedTASTyRelease = "3.0.0-M3-bin-20201215-cbe50b3-NIGHTLY" // TASTy version 26.1
```
Comment (sjrd) [inline project/DottySupport.scala]: Perhaps we can wait one more day to be able to use 3.0.0-M3 here ;)

**Review by sjrd — APPROVED** [review]

**Comment by sjrd** [comment]
Should we ignore the TRANSPARENT flag on traits? Is that new in M3 or was it already in M2? I forgot.

**Review by SethTisue — COMMENTED** [review]
LGTM, but as Seb notes let's wait to merge until M3 is out

**Comment by bishabosha** [comment]
> Should we ignore the TRANSPARENT flag on traits? Is that new in M3 or was it already in M2? I forgot.

yes, that was a change already made for M2 support

File: project/DottySupport.scala (hunk 1 above)
Comment (dwijnand) [reply project/DottySupport.scala]:
```suggestion
  val supportedTASTyRelease = "3.0.0-M3" // TASTy version 26.1
```

**Review by dwijnand — CHANGES_REQUESTED** [review]
Nice, thank you.

File: project/DottySupport.scala (hunk 1 above)
Comment (bishabosha) [reply project/DottySupport.scala]: done

File: project/DottySupport.scala [hunk 2]
```diff
@@ -12,8 +12,8 @@ import sbt.librarymanagement.{
   * Settings to support validation of TastyUnpickler against the release of dotty with the matching TASTy version
   */
 object TastySupport {
-  val supportedTASTyRelease = "3.0.0-M2" // TASTy version 25.1
-  val scala3Compiler = "org.scala-lang" % "scala3-compiler_3.0.0-M2" % supportedTASTyRelease
+  val supportedTASTyRelease = "3.0.0-M3" // TASTy version 26.1
+  val scala3Compiler = "org.scala-lang" % "scala3-compiler_3.0.0-M3" % supportedTASTyRelease
 }
```
Comment (nicolasstucki) [inline project/DottySupport.scala:17]: We can also update the version bellow
```diff
object DottySupport {
-  val dottyVersion = "3.0.0-M2"
+  val dottyVersion = "3.0.0-M3"
```

Comment (bishabosha) [reply project/DottySupport.scala:17]: I think that is usually changed in a separate PR

Comment (nicolasstucki) [reply project/DottySupport.scala:17]: OK

Comment (dwijnand) [reply project/DottySupport.scala:17]: Any reason to do it in a separate PR?  In the absence of reasons let's update both in this one, IMO.

Comment (bishabosha) [reply project/DottySupport.scala:17]: alright will do

**Review by dwijnand — APPROVED** [review]

**Comment by bishabosha** [comment]
dropped the commit to change `DottySupport.dottyVersion`, which is covered by https://github.com/scala/scala/pull/9395

**Comment by bishabosha** [comment]
I think the Travis error seems unrelated

**Comment by dwijnand** [comment]
Needs a rebase, the error is about not using sbt-dotty 0.5.

**Comment by bishabosha** [comment]
squashed and rebased

**Comment by bishabosha** [comment]
now the CI says the build fails to compile due to cyclic reference error

**Comment by dwijnand** [comment]
Could you rebase?  I can't push to the scalacenter org, even if it's a PR branch.

**Comment by bishabosha** [comment]
rebased

**Comment by bishabosha** [comment]
CI looks good
