### PR TITLE
SI-7612 Fix SOE regression in lubs

### PR DESCRIPTION
**Pull request by retronym**
The enclosed test case (whittled down lovingly from lift-mapper)
triggers the cycle in `elimSub`.

Regressed in a06d31f6a. The change was dicussed
https://github.com/scala/scala/pull/2022#discussion_r2832997.

This patch reverts to using `.underlying`.

Below, I've shown the different paths that are taken through
that method with before and after this patch. The key divergence
is when `<refinement>.this.M.dealias` reveals a captured existential
type symbol.

A more detailed look at how that happens:
   https://gist.github.com/retronym/5874775

Review by @adriaanm.

Targetting 2.10.x on grounds of locality of the fix and regression from 2.10.0 -> 2.10.1.

### CODE REVIEW

**Comment by lrytz** [comment]
what aobut https://github.com/scala/scala/pull/2600 ?

**Comment by retronym** [comment]
Right you are:

```
  [partest] testing: [...]/files/pos/lub-dealias-widen.scala                      [FAILED]
  [partest] lub-dealias-widen.scala:33: error: inferred type arguments [List[String] => String,List[String] => String] do not conform to method &'s type parameter bounds [G <: H,H >: Int => (Int => String)]
  [partest]   val s = r & r2
  [partest]             ^
  [partest] lub-dealias-widen.scala:33: error: type mismatch;
  [partest]  found   : Sitelet[List[String] => String]
  [partest]  required: Sitelet[G]
  [partest]   val s = r & r2
  [partest]               ^
  [partest] two errors found
```

I open the floor to suggestions.

**Comment by lrytz** [comment]
i didn't look at it, but there's no way to fix the infinite recursion in `dealiasWiden`?

**Comment by retronym** [comment]
`dealiasWiden` doesn't recurse. Its `elimSub` that does. You can see the cycle in the commit comment.

**Comment by lrytz** [comment]
i see - not sure right now what to do..

**Comment by adriaanm** [comment]
Closing this one for now.
