### PR TITLE
Support Scala 3 wildcard and renaming imports under -Xsource:3

### PR DESCRIPTION
**Pull request by smarter**
Instead of:

    import foo._

One can now write:

    import foo.*

and instead of:

    import foo.{bar => baz}

One can now write:

    import foo.{bar as baz}

As well as:

    import foo.bar as baz

This will let us deprecate the old syntax in a future release of Scala
3 (it's currently only deprecated under `-source future`).

See http://dotty.epfl.ch/docs/reference/changed-features/imports.html for
details but note that unlike Scala 3 this commit does not implement
support for:

    import java as j

As that would require deeper changes in the compiler.

### CODE REVIEW

**Review by lrytz — APPROVED** [review]

**Comment by hmemcpy** [comment]
Sorry for bumping this issue, I just noticed that this doesn't work in 2.13.6:

```scala
import scala.util.{Try, *}
```

I'm getting the error: `object * is not a member of package util`

This compiles just fine in Scala 3.

Is this a limitation of `-Xsource:3` or a possible bug?

**Comment by smarter** [comment]
@hmemcpy This is fixed in https://github.com/scala/scala/pull/9639

**Comment by hmemcpy** [comment]
Ah, cheers! Was this released?
I'm asking because IntelliJ's latest EAP is currently offering this refactoring for `-Xsource:3` users during "optimize usings", and it leaves broken code. I was about to report it there, next.

**Comment by smarter** [comment]
This PR will be part of 2.13.7.

**Comment by hmemcpy** [comment]
Thanks very much!
