### PR TITLE
Introduce `-Xsource-features`, for customizing the behavior of `-Xsource:3` and `-Xsource:3-cross`

### LINKED ISSUE #12961: Case companions no longer extends FunctionN under `-Xsource:3-cross`, breaks binary compatibility
2.13.13 aligned synthetic case companions with Scala 3 to no longer `extend FunctionN` under `-Xsource:3-cross` (https://github.com/scala/scala/pull/10648).

Projects that already have cross-published releases for Scala 2.13 and 3.x cannot adopt `-Xsource:3-cross` because this change is not binary compatible.

The workaround of manually writing out `object C extends FunctionN` is not a solution because that source change would also affect Scala 3, causing a binary incompatibility there. (It would also be very tedious.)

This situation can be a blocker for libraries to upgrade to Scala 2.13.13. Example:
  - On 2.13.12 with `-Xsource:3 -Xmigration`, the escape in`raw"\u0042"` is *not* processed
  - In 2.13.13 all semantic changes are moved to `-Xsource:3-cross`. A project using `-Xsource:3` needs to move to `-Xsource:3-cross` to maintain semantics. With `-Xsource:3`, the escape is now being processed.
  - The binary incompatibility of case companions comes in the way.

A more general question is how do we add further language changes to `-Xsoruce:3-cross` in the future. Every semantic change comes with a warning under `-Xsource:3`. But projects that are already on `3-cross` would silently get new semantics in a new Scala version.

### PR DESCRIPTION
**Pull request by som-snytt**
This feature is only recommended for projects that cross-build between Scala 2.13 and Scala 3. For migrating to Scala 3, use plain `-Xsource:3`. See also https://docs.scala-lang.org/scala3/guides/migration/tooling-scala2-xsource3.html.

This PR makes Scala 3 language features opt-in under an option "buffet" or "à la carte". To view the menu:

```
$> scalac -Xsource-features:help
Enable Scala 3 features under -Xsource:3.

Instead of `-Xsource-features:_`, it is recommended to enable specific features, for
example `-Xsource-features:v2.13.14,-case-companion-function` (-x to exclude x).
This way, new semantic changes in future Scala versions are not silently adopted;
new features can be enabled after auditing the corresponding migration warnings.

`-Xsource:3-cross` is a shorthand for `-Xsource:3 -Xsource-features:_`.

Features marked with [bin] affect the binary encoding. Enabling them in a project
with existing releases for Scala 2.13 can break binary compatibility.

Available features:

  case-apply-copy-access    Constructor modifiers are used for apply / copy methods of case classes. [bin]
  case-companion-function   Synthetic case companion objects no longer extend FunctionN. [bin]
  infer-override            Inferred type of member uses type of overridden member. [bin]
  any2stringadd             Implicit `any2stringadd` is never inferred.
  unicode-escapes-raw       Don't process unicode escapes in triple quoted strings and raw interpolations.
  string-context-scope      String interpolations always desugar to scala.StringContext.
  leading-infix             Leading infix operators continue the previous line.
  package-prefix-implicits  The package prefix p is no longer part of the implicit search scope for type p.A.
  implicit-resolution       Use Scala-3-style downwards comparisons for implicit search and overloading resolution (see github.com/scala/scala/pull/6037).
  v2.13.13                  case-apply-copy-access,case-companion-function,infer-override,any2stringadd,unicode-escapes-raw,string-context-scope,leading-infix,package-prefix-implicits.
  v2.13.14                  v2.13.13 plus implicit-resolution
```

`-Xsource:3 -Xsource-features:_` (or `-Xsource:3-cross` for convenience to start a REPL) offers all "courses" as "prix fixe". It's not recommended in a build script, use `v2.13.14` instead to get migration warnings as new features are adopted.

`-Xmigration` is no longer "overloaded" to mean `-Wconf:cat=scala3-migration:w`. That incantation must be written in full.

Fixes scala/bug#12961

### CODE REVIEW

**Comment by som-snytt** [comment]
To be squashed after review. Nominally (whatever that weaselly word means), I checked usages of `isScala3...` for reasonableness, but it's surprisingly difficult to verify. A clearer API would be more like `hardMigration`: either `migrationWarning` if `isScala3`, or discriminating `progressiveWarning(at2 = old_behavior, at3 = warn, at3X = cross)` where cross warns if verbose.

The `-Ysource-options:case-access` warning for `apply` is an unduly heavyweight mechanism for a niche feature or warning.

**Comment by SethTisue** [comment]
associated doc change PR https://github.com/scala/docs.scala-lang/pull/2994

**Comment by lrytz** [comment]
Thank you for getting it rolling, I was going to pick it up this week.

I'm forming somewhat strong opinions about providing multiple ways to do the same thing. It takes time for people to learn / look up what all those variants mean.
  - `-Xsource:3` is what it is in 2.13.13, that's good
  - `-Ysource-options` could work with `-Xsource:3`, we don't need `-Xsource:3-compat` for that
  - `-Xsource:3-cross` is the same as `-Ysource-options:_`
  - `-Xsource:3-migration` is the same as `-Xsource:3 -Wconf:cat=scala3-migration:w`
  - I agree to stop the `-Xmigration` overload of course

Compiler flags are not code, they are only touched once in a while and don't need to be as succinct as possible.

The current proposal also doesn't really solve the auditing problem. If I'm using `3-compat` and upgrade to a new Scala that adds some semantic change, how do I find out? I can go back to `3` but then the new warnings are mixed up with all the older warnings which I already addressed. So instead of `3-compat`, I think it's better to add all semantic changes to `-Ysource-options`, not just the ones affecting binary encoding.

I'll give it a go today and push to this PR.

**Comment by som-snytt** [comment]
Happy to have you progress this experiment to your liking.

Here, you find out "what's new" by `-Ysource-options:verbose` (if you triggered it) or `help` (IIRC there was help text).

I think just having `-Xnew-stuff:case-access` etc is fine, in the xlint mode; I just wanted to see if we could avoid it, because it results in "fine-tuning". The experiment here was `3-compat` allows for opt-in to dangerous options. So there was the conservative flag, the all-in flag, and the goldilocks flag.

Here, `-Xsource:3-migration` is just an alias for `-Xsource:3`, for clarity.

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 1]
```diff
@@ -1128,7 +1128,7 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
       def adaptApplyInsertion(): Tree = doAdaptApplyInsertion(retry = false)
 
       def doAdaptApplyInsertion(retry: Boolean): Tree =
-        if (currentRun.isScala3Cross && !isPastTyper && tree.symbol != null && tree.symbol.isModule && tree.symbol.companion.isCase && isFunctionType(pt))
+        if (currentRun.isScala3X && !isPastTyper && tree.symbol != null && tree.symbol.isModule && tree.symbol.companion.isCase && isFunctionType(pt))
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala]: I realize that apply insertion should be enabled by default, not even under `-Xsource:3`.

For a library built with `-Xsoruce:3-cross`, case class companions don't extend `FunctionN`. This should not break `List(1).map(A)` for users of the library that use the default compiler options.

@som-snytt wdyt?

Comment (som-snytt) [reply src/compiler/scala/tools/nsc/typechecker/Typers.scala]: The library would use `3-compat` (or equivalent) to avoid incompatible changes.

The librarian, for the same reason, would not add `object A` companion that has the same effect; or would be sorry if they did.

But you may be right that this should be considered a "benign" feature change that everyone could benefit from. Fork all the language features! It is of general utility. The downside is your 2.12 build breaks; but who does that? I guess only middle-size fish who consume smaller fish and are consumed in turn.

**Comment by lrytz** [comment]
We might rename `-Ysource-options`

Also I could probably live with an alias `Xsource:3-cross` for `-Ysource-options:_`, it would be handy for testing stuff (not just for us, also for actual users of `Ysource-options` when they want to fire up a REPL).

File: src/compiler/scala/tools/nsc/typechecker/Unapplies.scala [hunk 2]
```diff
@@ -98,25 +98,31 @@ trait Unapplies extends ast.TreeDSL {
...
+    def isInherit(access: Flags): Boolean = access.&(Inherit) != 0
+  }
+  private def applyAccess(mods: Modifiers): ApplyAccess.Flags = {
+    import ApplyAccess._
     val changeModsIn3 = mods.hasFlag(PRIVATE) || (!mods.hasFlag(PROTECTED) && mods.hasAccessBoundary)
-    if (currentRun.isScala3Cross && changeModsIn3) Inherit
-    else if (currentRun.isScala3 && changeModsIn3) Warn
+    if (!changeModsIn3) Default
+    else if (currentRun.scala3Features.caseApplyCopyAccess) Inherit
+    else if (currentRun.isScala3) Warn
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Unapplies.scala:114]: These changes were to say "both inherit and warn about it". That's not needed because why? If they ask for it via option, it should never warn. Oder?

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala [hunk 3]
```diff
@@ -3477,7 +3484,9 @@ trait Typers extends Adaptations with Tags with TypersTracking with PatternTyper
               if (!sym.initialize.hasFlag(IS_ERROR)) {
                 newStats += typedStat(tree) // might add even more synthetics to the scope
                 tree.getAndRemoveAttachment[CaseApplyInheritAccess.type].foreach(_ =>
-                  runReporting.warning(tree.pos, "access modifiers for `apply` method are copied from the case class constructor", Scala3Migration, sym))
+                  runReporting.warning(tree.pos, "access modifiers for `apply` method were copied from the case class constructor under Scala 3", Scala3Migration, sym))
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Typers.scala]: Wasn't sure the extra attachment would be needed if you only get cross-features you asked for, but now I'm not sure what the warning policy is. I will continue reading...

File: src/compiler/scala/tools/nsc/typechecker/Unapplies.scala [hunk 4]
```diff
@@ -163,10 +169,13 @@ trait Unapplies extends ast.TreeDSL {
...
     val access = applyAccess(inheritedMods)
     val mods =
-      if (access == Inherit) (caseMods | (inheritedMods.flags & PRIVATE)).copy(privateWithin = inheritedMods.privateWithin)
+      if (ApplyAccess.isInherit(access)) (caseMods | (inheritedMods.flags & PRIVATE)).copy(privateWithin = inheritedMods.privateWithin)
       else caseMods
     factoryMeth(mods, nme.apply, cdef).tap(m =>
-      if (access == Warn) m.updateAttachment(CaseApplyInheritAccess))
+      if (ApplyAccess.isWarn(access))
+        if (ApplyAccess.isInherit(access)) m.updateAttachment(CaseApplyInheritAccess)
+        else m.updateAttachment(CaseApplyInheritAccessMigration)
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Unapplies.scala]: IIUC it is no longer both warn + inherit, so only one attachment is needed?

File: src/compiler/scala/tools/nsc/Global.scala [hunk 5]
```diff
@@ -1180,12 +1180,23 @@ class Global(var currentSettings: Settings, reporter0: Reporter)
...
+      def caseApplyCopyAccess    = isScala3 && contains(o.caseApplyCopyAccess)
+      def caseCompanionFunction  = isScala3 && contains(o.caseCompanionFunction)
+      def inferOverride          = isScala3 && contains(o.inferOverride)
+      def any2StringAdd          = isScala3 && contains(o.any2StringAdd)
+      def unicodeEscapesRaw      = isScala3 && contains(o.unicodeEscapesRaw)
+      def stringContextScope     = isScala3 && contains(o.stringContextScope)
+      def leadingInfix           = isScala3 && contains(o.leadingInfix)
+      def packagePrefixImplicits = isScala3 && contains(o.packagePrefixImplicits)
+      def implicitResolution     = isScala3 && contains(o.implicitResolution) || settings.Yscala3ImplicitResolution.value
+    }
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/Global.scala:1198]: A "choice" use of the facility!  Also nice to fold that "implicit resolution" option into the menu.

File: src/compiler/scala/tools/nsc/typechecker/Unapplies.scala [hunk 6]
```diff
@@ -285,11 +294,10 @@ trait Unapplies extends ast.TreeDSL {
         if (currentRun.isScala3) {
           val inheritedMods = constrMods(cdef)
           val mods3 = Modifiers(SYNTHETIC | (inheritedMods.flags & AccessFlags), inheritedMods.privateWithin)
-          if (currentRun.isScala3Cross)
-            mods3
+          if (currentRun.scala3Features.caseApplyCopyAccess) mods3
           else {
             if (mods3 != synth)
-              runReporting.warning(cdef.pos, "access modifiers for `copy` method are copied from the case class constructor", Scala3Migration, cdef.symbol)
+              runReporting.warning(cdef.namePos, "access modifiers for `copy` method will be copied from the case class constructor under Scala 3", Scala3Migration, cdef.symbol)
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Unapplies.scala]: this was a tweak to tighten the span of the diagnostic. Eventually someone using metals would notice.

The apply method is still just the tree focus because I was too lazy to downcast. Or I was too downcast.

File: src/compiler/scala/tools/nsc/typechecker/Unapplies.scala (hunk 2 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/typechecker/Unapplies.scala:114]: That's how I see it, there should no warning for using features that you opted in.

File: src/compiler/scala/tools/nsc/typechecker/Typers.scala (hunk 3 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/typechecker/Typers.scala]: One of the two annotations is stale now, it's either warn or new semantics

**Comment by lrytz** [comment]
I squashed almost everything into one commit, only a few semantic changes as separate commits as good as possible.

File: src/compiler/scala/tools/nsc/settings/ScalaSettings.scala [hunk 7]
```diff
@@ -144,31 +147,72 @@ trait ScalaSettings extends StandardScalaSettings with Warnings { _: MutableSett
...
+          |
+          |Instead of `-Xsource-features:_`, it is recommended to enable specific features, for
+          |example `-Xsource-features:v2.13.14,-case-companion-function` (-x to exclude x).
+          |This way, new semantic changes in future Scala versions are not silently adopted;
+          |new features can be enabled after auditing the corresponding migration warnings.
+          |
+          |`-Xsource:3-cross` is a shorthand for `-Xsource:3 -Xsource-features:_`.
+          |
+          |Available features:
+          |""".stripMargin)
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/settings/ScalaSettings.scala]: extra strip (it would be interesting if that failed to compile)

File: test/files/run/print-args.scala [hunk 8]
```diff
@@ -26,6 +27,7 @@ object Test extends DirectTest {
     """
   def show() = {
     assert(!compile())
+    //assertEquals(expected.linesIterator.toList, Files.readAllLines(argfile).asScala.toList)
```
Comment (som-snytt) [inline test/files/run/print-args.scala:30]: debug cruft. The `expected` needs `.trim` and assert could be
```
    import scala.tools.testkit.AssertUtil.assertSameElements
    assertSameElements(expected.linesIterator, Files.readAllLines(argfile).asScala)
```
The test is because `-Vprint-args` was broken; the `-Xsource` is not relevant.

I'll submit the tweak separately. :)

File: src/compiler/scala/tools/nsc/settings/ScalaSettings.scala (hunk 7 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/settings/ScalaSettings.scala]: 👍 IntelliJ adds it when typing `sm"""<return>`...

**Comment by som-snytt** [comment]
The buffet option makes it easier to see in the source where the features take effect.

It also simplifies the warnings under the rule of "no warning if they asked for a feature". (I just remembered that the point of `verbose` mode was to enable "audit", so you could see "this override was inferred differently", for example. Reverting to migration might show the future warning, but it might also just show an error?) (Probably no one would ever use verbose audit anyway.)

It took me two tries to correctly test moving the "case function" check from ident to adapt. Very nice!

**Comment by som-snytt** [comment]
LGTM. Lukas pulled that old github mind trick where he gets me to open the PR so that only he can approve it later. :)

I partially edited the OP comment, which is probably still inaccurate.

**Comment by som-snytt** [comment]
Your old trick of emitting the "how to suppress it" message would be helpful, especially when the category differs if not `-Xsource:3`.

https://discord.com/channels/632150470000902164/632150470000902166/1217725189018615848

**Comment by som-snytt** [comment]
travis claims
```
-t12919.scala:48: error: Implicit method myClassToSeq was found in a package prefix of the required type, which is not part of the implicit scope in Scala 3.

+t12919.scala:48: error: Implicit method myClassToSeq was found in a package prefix of the required type, which is not part of the implicit scope in Scala 3 (or with -Xsource-features:package-prefix-implicits).
```

**Comment by lrytz** [comment]
semantic merge conflict with https://github.com/scala/scala/pull/10706, rebased.

> Your old trick of emitting the "how to suppress it" message would be helpful

Maybe somebody will eventually figure out how to do interactive verbose (not "re-run with ...").

```
➜ sandbox s -Wconf:any:wv
> scala repl -S 2.13 -cp . -Wconf:any:wv
Welcome to Scala 2.13.13 (OpenJDK 64-Bit Server VM, Java 21.0.1).
Type in expressions for evaluation. Or try :help.

scala> implicit val x = 41
                    ^
       warning: Implicit definition should have explicit type (inferred Int) [quickfixable]
       Applicable -Wconf / @nowarn filters for this warning: msg=<part of the message>, cat=other-implicit-type, site=x
val x: Int = 41
```

**Comment by SethTisue** [comment]
I'm noticing in the community build that despite this change:

> -Xmigration is no longer "overloaded" to mean -Wconf:cat=scala3-migration:w. That incantation must be written in full.

I'm still seeing errors like:

```
[playframework] [error] Scala 3 migration messages are errors under -Xsource:3. Use -Wconf / @nowarn to filter them or add -Xmigration to demote them to warnings.
```

seems like an oversight that this advice wasn't updated?

**Comment by som-snytt** [comment]
I never read those messages all the way to the end.

Edit: until now. Tweak at https://github.com/scala/scala/pull/10718

**Comment by SethTisue** [comment]
a bit of good news: over in the community build, I removed `-Xmigration` from about a two dozen repos and only had to replace it with `-Wconf:cat=scala3-migration:w` in five:

```
proj/blaze.conf:    "appendScalacOptions -Wconf:cat=scala3-migration:w"
proj/json4s.conf:    "appendScalacOptions -Wconf:cat=scala3-migration:w"
proj/mima.conf:    "appendScalacOptions -Wconf:cat=scala3-migration:w"
proj/playframework.conf:    "appendScalacOptions -Wconf:cat=scala3-migration:w"
proj/scalafx.conf:    "appendScalacOptions -Wconf:cat=scala3-migration:w"
```

**Comment by ghostbuster91** [comment]
Hi, this is really great feature. Unfortunately many projects that cross-build for 2.13 also cross-build for 2.12. Are there any chances/plans of getting this backported into 2.12 line?

**Comment by SethTisue** [comment]
@ghostbuster91 in short, no. the ambition (and risk) level here exceeds what remains possible in the 2.12 line
