### PR TITLE
Remove wildcardToTypeVarMap

### LINKED ISSUE #11579: scala 2.13.0 compiler crashes with no-symbol does not have a type constructor
## Scala version

```
$ scalac -version
Scala compiler version 2.13.0 -- Copyright 2002-2019, LAMP/EPFL and Lightbend, Inc.
```

## Java version

```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

and

```
$ java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)
```

## code

```scala
package foo

object Foo {
  import scala.collection.generic.IsIterable
  import scala.language.implicitConversions

  class Ops[I] {
    def method: Unit = ()
  }

  implicit def ToOps[Repr, L, R](aCol: Repr)(implicit isIterable: IsIterable[Repr]{type A = (L, R)}): Ops[isIterable.type] = new Ops[isIterable.type]

  List(1 -> 2).method
}
```

## error

```
$ scalac Foo.scala 
error:
  no-symbol does not have a type constructor (this may indicate scalac cannot find fundamental classes)
     while compiling: Foo.scala
        during phase: typer
     library version: version 2.13.0
    compiler version: version 2.13.0
  reconstructed args:

  last tree to typer: Ident(<argument>)
       tree position: line 13 of Foo.scala
            tree tpe: List[(Int, Int)]
              symbol: <none>
   symbol definition: <none> (a NoSymbol)
      symbol package: <none>
       symbol owners:
           call site: object Foo in package foo in package foo

== Source file context for tree position ==

    10
    11   implicit def ToOps[Repr, L, R](aCol: Repr)(implicit isIterable: IsIterable[Repr]{type A = (L, R)}): Ops[isIterable.type] = new Ops[isIterable.type]
    12
    13   List(1 -> 2).method
    14 }
    15
error: scala.reflect.internal.FatalError:
  no-symbol does not have a type constructor (this may indicate scalac cannot find fundamental classes)
     while compiling: Foo.scala
        during phase: typer
     library version: version 2.13.0
    compiler version: version 2.13.0
  reconstructed args:

  last tree to typer: Ident(<argument>)
       tree position: line 13 of Foo.scala
            tree tpe: List[(Int, Int)]
              symbol: <none>
   symbol definition: <none> (a NoSymbol)
      symbol package: <none>
       symbol owners:
           call site: object Foo in package foo in package foo

== Source file context for tree position ==

    10
    11   implicit def ToOps[Repr, L, R](aCol: Repr)(implicit isIterable: IsIterable[Repr]{type A = (L, R)}): Ops[isIterable.type] = new Ops[isIterable.type]
    12
    13   List(1 -> 2).method
    14 }
    15
	at scala.reflect.internal.Reporting.abort(Reporting.scala:68)
	at scala.reflect.internal.Reporting.abort$(Reporting.scala:64)
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:28)
	at scala.reflect.internal.Symbols$Symbol.typeConstructor(Symbols.scala:1484)
	at scala.reflect.internal.Types$$anon$2.apply(Types.scala:1723)
	at scala.reflect.internal.Types$$anon$2.apply(Types.scala:1720)
	at scala.reflect.internal.Types$TypeRef.mapOver(Types.scala:2355)
	at scala.reflect.internal.Types$$anon$2.apply(Types.scala:1726)
	at scala.reflect.internal.Types$$anon$2.apply(Types.scala:1720)
	at scala.reflect.internal.Symbols$Symbol.modifyInfo(Symbols.scala:1565)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:141)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:127)
	at scala.reflect.internal.Types.defineBaseTypeSeqOfCompoundType(Types.scala:1730)
	at scala.reflect.internal.Types.defineBaseTypeSeqOfCompoundType$(Types.scala:1709)
	at scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfCompoundType(SymbolTable.scala:28)
	at scala.reflect.internal.Types$CompoundType.baseTypeSeq(Types.scala:1617)
	at scala.reflect.internal.Types$CompoundType.baseTypeSeqDepth(Types.scala:1625)
	at scala.reflect.internal.Types$NullaryMethodType.baseTypeSeqDepth(Types.scala:2914)
	at scala.reflect.internal.Types.$anonfun$baseTypeSeqDepth$1(Types.scala:4427)
	at scala.reflect.internal.Depth$.maximumBy(Depth.scala:59)
	at scala.reflect.internal.Types.baseTypeSeqDepth(Types.scala:4427)
	at scala.reflect.internal.Types.lubDepth(Types.scala:4411)
	at scala.reflect.internal.Types.lubDepth$(Types.scala:4409)
	at scala.reflect.internal.SymbolTable.lubDepth(SymbolTable.scala:28)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.scala$tools$nsc$typechecker$Implicits$ImplicitSearch$$matchesPtInst(Implicits.scala:694)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.rankImplicits(Implicits.scala:1128)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.findBest(Implicits.scala:1164)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1221)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1646)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit1(Implicits.scala:113)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:92)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:89)
	at scala.tools.nsc.Global$$anon$5.inferImplicit(Global.scala:482)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitFor(Implicits.scala:47)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitFor$(Implicits.scala:46)
	at scala.tools.nsc.Global$$anon$5.inferImplicitFor(Global.scala:482)
	at scala.tools.nsc.typechecker.Typers$Typer.applyImplicitArgs(Typers.scala:271)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit1(Implicits.scala:849)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit0(Implicits.scala:801)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.scala$tools$nsc$typechecker$Implicits$ImplicitSearch$$typedImplicit(Implicits.scala:621)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.rankImplicits(Implicits.scala:1129)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.findBest(Implicits.scala:1164)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1221)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1620)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit1(Implicits.scala:113)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:92)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:89)
	at scala.tools.nsc.Global$$anon$5.inferImplicit(Global.scala:482)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitView(Implicits.scala:51)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitView$(Implicits.scala:50)
	at scala.tools.nsc.Global$$anon$5.inferImplicitView(Global.scala:482)
	at scala.tools.nsc.typechecker.Typers$Typer.inferView(Typers.scala:337)
	at scala.tools.nsc.typechecker.Typers$Typer.adaptToMember(Typers.scala:1339)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adaptToMemberWithArgs$7(Typers.scala:1389)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:715)
	at scala.tools.nsc.typechecker.Typers$Typer.adaptToMemberWithArgs(Typers.scala:1389)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelect$1(Typers.scala:5115)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:5266)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5822)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5931)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3396)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3396)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2050)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1925)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5776)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5931)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3396)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3396)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5475)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5778)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:115)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:451)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:104)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1510)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1494)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1486)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1615)
	at scala.tools.nsc.Driver.doCompile(Driver.scala:48)
	at scala.tools.nsc.MainClass.doCompile(Main.scala:30)
	at scala.tools.nsc.Driver.process(Driver.scala:68)
	at scala.tools.nsc.Driver.main(Driver.scala:82)
	at scala.tools.nsc.Main.main(Main.scala)
```

### PR DESCRIPTION
**Pull request by joroKr21**
There exists only one test which needed an update.
Coincidentally, it never converted a wildcard to a typevar.
Instead it must have relied upon a side effect ot typemaps?
Unreachable cases were removed in response to warnings.
Also I heard existentials are out of fashion.

Fixes scala/bug#11579 which regressed in #7376 as an alternative to #8248

### CODE REVIEW

**Comment by joroKr21** [comment]
Apropos the original test fails with:
```scala
existentials.scala:63: error: cyclic aliasing or subtyping involving type T
       val c = ctr.newCounter
           ^
existentials.scala:69: error: cyclic aliasing or subtyping involving type T
       val c = ctr.newCounter
```

File: src/reflect/scala/reflect/internal/Types.scala [hunk 1]
```diff
@@ -3667,13 +3667,7 @@ trait Types
 
       if (suspended) tp =:= origin
       else if (instValid) checkIsSameType(tp)
-      else isRelatable(tp) && {
-        val newInst = wildcardToTypeVarMap(tp)
```
Comment (adriaanm) [inline src/reflect/scala/reflect/internal/Types.scala:3671]: The only rationale for the type vars that I can come up with is that they, unlike wildcards, can/will make sure that they can be instantiated to a valid type. A wildcard will just accept any comparison to another type, while a type var tracks the comparisons and in the end makes sure the accumulated lower bounds are compatible with the accumulated upper bounds. Maybe that check isn't happening properly, and thus the typevars are indistinguishable from wildcards, but I'd like to explore that hypothesis more (or if you did, record the exploration) before dropping them.

Comment (adriaanm) [reply src/reflect/scala/reflect/internal/Types.scala:3671]: I'm having trouble convincing myself this is actually important, since each wildcard is instantiated to a fresh type var -- so, how can they ever accumulate incompatible bounds?

Comment (joroKr21) [reply src/reflect/scala/reflect/internal/Types.scala:3671]: Hmm, good point. I guess it depends on the call to `constr isWithinBounds newInst`, but when are those new type variables ever instantiated?

Comment (joroKr21) [reply src/reflect/scala/reflect/internal/Types.scala:3671]: @adriaanm WDYT about this: I make a PR with an assertion that we never instantiate type variables with wildcard origin and we let CI check that. Then we can run a community build, right? I don't know another way to check this. Here it is: #8283

Comment (adriaanm) [reply src/reflect/scala/reflect/internal/Types.scala:3671]:
```
    def isWithinBounds(tp: Type): Boolean = (
         lobounds.forall(_ <:< tp)
      && hibounds.forall(tp <:< _)
      && (numlo == NoType || (numlo weak_<:< tp))
      && (numhi == NoType || (tp weak_<:< numhi))
    )
```

is kind of a lightweight instantiate? Trying to reverse the intent here, not sure.

Comment (joroKr21) [reply src/reflect/scala/reflect/internal/Types.scala:3671]: You mean on the type which was the result of `wildcardToTypeVarMap`?  Sure but this would only accumulate bounds in the freshly baked type variables. My hypothesis is that we never instantiate them and the accumulated bounds don't matter.

Comment (adriaanm) [reply src/reflect/scala/reflect/internal/Types.scala:3671]: yeah, so maybe we should run a similar check on all freshly created type vars?

Comment (adriaanm) [reply src/reflect/scala/reflect/internal/Types.scala:3671]: Sorry, I'm not being very clear. After we check `isWithinBounds`, we should probably check that there's actually a solution for the constraints implied by freshly created type vars, now that they've been constrained. If we don't do that, I agree it's equivalent to the cleanup in your PR.

Comment (adriaanm) [reply src/reflect/scala/reflect/internal/Types.scala:3671]: So the question becomes: *should* we indeed check that they can be instantiated? I don't know.

Comment (joroKr21) [reply src/reflect/scala/reflect/internal/Types.scala:3671]: Ah I see, I did not think of that. Makes sense, we can try that too :+1:

Comment (adriaanm) [reply src/reflect/scala/reflect/internal/Types.scala:3671]: Thanks for investigating! I know it can get a bit annoying to figure out the original intent in this part of the code base :-)

Comment (joroKr21) [reply src/reflect/scala/reflect/internal/Types.scala:3671]: Actually I couldn't find an easy way to instantiate the type variables at this point. `solve` expects also a list of type parameters and other methods which I could use are in `Infer` and not accessible here. Any pointers?

**Review by adriaanm — APPROVED** [review]

**Comment by lrytz** [comment]
@adriaanm @joroKr21 this caused an infinite recursion when compiling slick
  - see https://github.com/scala/scala-dev/issues/652
  - the log https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2578/artifact/logs/slick-build.log

To reproduce, clone https://github.com/slick/slick, check out revision `16545a69`, run
```
sbt ++2.13.1-bin-b3c13e8 'set resolvers += "scala-integration" at "https://scala-ci.typesafe.com/artifactory/scala-integration/"' testkit/compile
```

**Comment by adriaanm** [comment]
Ok, could you revert this PR and I’ll investigate after the release. I’m off today.

**Comment by lrytz** [comment]
👍

**Comment by joroKr21** [comment]
Sorry about that, I really thought the community build we ran with the assertion that said typevars are not instantiated would be enough but I was wrong. I wonder whether this has anything to do with wildcards or it's just the side effect of a type map, I might have time to check over the weekend but no promises.

**Comment by joroKr21** [comment]
@lrytz @adriaanm confirmed that `slick` revision `16545a69` breaks without `wildcardToTypeVarMap` (`StackOverflowError`) but it compiles fine with the following patch:

```diff
--- a/src/reflect/scala/reflect/internal/tpe/TypeMaps.scala
+++ b/src/reflect/scala/reflect/internal/tpe/TypeMaps.scala
@@ -1007,10 +1007,7 @@ private[internal] trait TypeMaps {
   /** A map to convert every occurrence of a wildcard type to a fresh
     *  type variable */
   object wildcardToTypeVarMap extends TypeMap {
-    def apply(tp: Type): Type = tp match {
-      case pt: ProtoType => TypeVar(tp, new TypeConstraint(pt.toBounds))
-      case _ => tp.mapOver(this)
-    }
+    def apply(tp: Type): Type = tp.mapOver(this)
   }
 
   /** A map to convert each occurrence of a type variable to its origin. */
```

I guess it has something to do with the side effects caused by an identity `TypeMap`?

Edit: Maybe this (`TypeVar.mapOver`):

```scala
    override def mapOver(map: TypeMap): Type =
      if (constr.instValid) {
        // ideally TypeVar.inst should handle this,
        // but it would have to be disentangled from TypeVar.constr.inst
        map(appliedType(constr.inst, typeArgs))
      } else map match {
        case map: VariancedTypeMap =>
          //@M !args.isEmpty implies !typeParams.isEmpty
          applyArgs(map.mapOverArgs(typeArgs, params))
        case _ => applyArgs(typeArgs mapConserve map)
      }
```

Yep, this also fails:

```diff
--- a/src/reflect/scala/reflect/internal/tpe/TypeMaps.scala
+++ b/src/reflect/scala/reflect/internal/tpe/TypeMaps.scala
@@ -1008,7 +1008,7 @@ private[internal] trait TypeMaps {
     *  type variable */
   object wildcardToTypeVarMap extends TypeMap {
     def apply(tp: Type): Type = tp match {
-      case pt: ProtoType => TypeVar(tp, new TypeConstraint(pt.toBounds))
+      case tv: TypeVar => tv
       case _ => tp.mapOver(this)
     }
   }
```
