### PR TITLE
Regression test cyclic reference

### LINKED ISSUE #10639: 'illegal cyclic inheritance involving class' with Java enums
Attempting to write Scala code that relies on Java enums which implement an interface with a static method that captures the enum type as a method parameter, causes the `illegal cyclic inheritance involving class` error to occur during compilation. The caveat is to make sure the Scala class is compiled on its own, e.g. the Java enum and interface could be compiled separately and packaged into a JAR file. Another way to induce consistent failures is to explicitly set compile order to `JavaThenScala`, i.e.: `compileOrder := CompileOrder.JavaThenScala`.

Reproducible using SBT 1.0.3 with Scala versions 2.11.8, 2.12.3, 2.12.4

```
//Identifiable.java
package com.example;

import java.util.Map;
import java.util.function.Function;
import java.util.stream.Stream;

import static java.util.stream.Collectors.toMap;

public interface Identifiable {
    String name();

    static <E extends Enum<E> & Identifiable> Map<String, E> valuesByName(final E[] values) {
        return Stream.of(values).collect(toMap(Identifiable::name, Function.identity()));
    }
}
```

```
//Size.java
package com.example;

public enum Size implements Identifiable {
    SMALL, MEDIUM, LARGE;
}
```

```
//Broken.scala
package com.example

object Broken extends App {
  println(Size.SMALL)
}
```

```
//build.sbt
scalaVersion := "2.12.4" //or 2.11.8 or 2.12.3
compileOrder := CompileOrder.JavaThenScala
```

> [error] /tmp/doyousee/src/main/scala/com/example/Broken.scala:4:10: illegal cyclic inheritance involving class Size
> [error]   println(Size.SMALL)
> [error]          ^
> [error] one error found
> [error] (compile:compileIncremental) Compilation failed

Possibly related #3809 (using `-Ybreak-cycles` option had no effect).

Originally asked on StackOverflow: [How to resolve “Illegal cyclic inheritance” compilation error when using a Java enum in Scala?](https://stackoverflow.com/questions/47611159/how-to-resolve-illegal-cyclic-inheritance-compilation-error-when-using-a-java?noredirect=1#comment82182229_47611159)

### PR DESCRIPTION
**Pull request by som-snytt**
Closes scala/bug#10639

### CODE REVIEW

**Comment by SethTisue** [comment]
🙏 

this resurfaced old ticket brought to us by https://www.codetriage.com
