### PR TITLE
Emit mixin forwarders as ordinary, non-bridge methods again

### LINKED ISSUE #11484: Lack of bridges for classes extending traits with erased overloads prevent extension in java
given

```
class Foo[A]
sealed trait Trait[A] {
  def overloaded(that: List[Trait[A]]): Trait[A] = that.head
  def overloaded(that: List[Foo[A]]): Foo[A] = that.head
}
abstract class AbstractClass[A] extends Trait[A]
```

a java class 

```
public class Failure extends AbstractClass<String>{
}
```

used to be possible, but is impossible in 2.13.0-RC1, and fails with

`name clash: <A>overloaded(scala.collection.immutable.List<example.Foo<A>>) in example.Trait and <A>overloaded(scala.collection.immutable.List<example.Trait<A>>) in example.Trait have the same erasure, yet neither overrides the other`

This regressed in https://github.com/scala/scala/pull/7843

### LINKED ISSUE #11512: Compilation error when subclassing a class with methods inherited from a trait with mixin from Java
Not sure if the title correctly summarizes the problem, but the following compiled with 2.13.0-M5, but not on RC1:

Scala:

```scala
trait SuiteMixin { this: Suite =>
  def rerunner: Option[String]
}
trait Suite {
  def rerunner: Option[String] = ???
}
abstract class JournalSpec extends Suite with SuiteMixin
```

Java:

```java
class MyJournalSpecTest extends JournalSpec {
}
```

Compiler error:

```
[error] /home/aengelen/dev/scala-2.13-repro/src/main/java/MyJournalSpecTest.java:1:1: MyJournalSpecTest is not abstract and does not override abstract method rerunner() in SuiteMixin
[error] class MyJournalSpecTest extends JournalSpec {
[error] (Compile / compileIncremental) javac returned non-zero exit code
```

Looking at the generated classes, `Suite` and `SuiteMixin` are the same between M5 and RC1:

```java
Compiled from "Suite.scala"
public interface Suite {
  public static scala.Option rerunner$(Suite);
  public scala.Option<java.lang.String> rerunner();
  public static void $init$(Suite);
}

Compiled from "SuiteMixin.scala"
public interface SuiteMixin {
  public abstract scala.Option<java.lang.String> rerunner();
}
```

But `JournalSpec` is different: on RC1 it is missing the `<java.lang.String>` generic on the `rerunner` return type:

```java
javap ./target/scala-2.13.0-RC1/classes/JournalSpec.class
Compiled from "JournalSpec.scala"
public abstract class JournalSpec implements Suite,SuiteMixin {
  public scala.Option rerunner();
  public JournalSpec();
}

javap ./target/scala-2.13.0-M5/classes/JournalSpec.class
Compiled from "JournalSpec.scala"
public abstract class JournalSpec implements Suite,SuiteMixin {
  public scala.Option<java.lang.String> rerunner();
  public JournalSpec();
}
```

### PR DESCRIPTION
**Pull request by lrytz**
Reverts https://github.com/scala/scala/pull/7980 and https://github.com/scala/scala/pull/7843, as discussed on https://github.com/scala/bug/issues/11512.

Fixes https://github.com/scala/bug/issues/11484, fixes https://github.com/scala/bug/issues/11512.

Reopens https://github.com/scala/bug/issues/8905. 

cc @sjrd.

### CODE REVIEW

**Comment by sjrd** [comment]
> cc @sjrd.

Thanks for letting me know. This is not an issue for Scala.js, as anyway we fixed the original Scala.js thing in https://github.com/scala-js/scala-js/pull/3584 for earlier versions of Scala. That fix will work equally well for 2.13.x with the present PR merged.

**Review by smarter — APPROVED** [review]
I think https://github.com/scala/scala/pull/7980 could be kept, but I'll let you decide.
