### PR TITLE
Ignore conversion to type with inaccessible member

### LINKED ISSUE #11787: Inaccessible method can cause implicit conversion search to fail
This code doesn't compile:

```scala
object syntax {
  implicit class Ops1(x: String) { private[syntax] def bar: Int = 1 }
  implicit class Ops2(x: String) { def bar: Int = 2 }
}

object test {
  import syntax._
  val result = "foo".bar
}
```

The error message says there's an ambiguity:

```scala
[error] /home/travis/tmp/so/syntax/src/main/scala/test.scala:9:16: type mismatch;
[error]  found   : String("foo")
[error]  required: ?{def bar: ?}
[error] Note that implicit conversions are not applicable because they are ambiguous:
[error]  both method Ops1 in object syntax of type (x: String)syntax.Ops1
[error]  and method Ops2 in object syntax of type (x: String)syntax.Ops2
[error]  are possible conversion functions from String("foo") to ?{def bar: ?}
[error]   val result = "foo".bar
[error]                ^
[error] /home/travis/tmp/so/syntax/src/main/scala/test.scala:9:22: value bar is not a member of String
[error]   val result = "foo".bar
[error]                      ^
[error] two errors found
```
The following also fails (as expected):
```scala
object syntax {
  implicit class Ops1(x: String) { private[syntax] def bar: Int = 1 }
}

object test {
  import syntax._
  val result = "foo".bar
}
```
Because:
```scala
[error] /home/travis/tmp/so/syntax/src/main/scala/test.scala:9:22: method bar in class Ops1 cannot be accessed in syntax.Ops1
[error]   val result = "foo".bar
[error]                      ^
[error] one error found
```
So a method that isn't actually a candidate for the implicit conversion can still cause the search to fail because of ambiguity.

I've confirmed that the code above doesn't compile on 2.11.12, 2.12.10, and 2.13.1. The problem looks vaguely familiar to me but I couldn't find a previous report.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#11787

Spec already says inaccessible `e.m` doesn't stop search, so extend that to targets of conversions.

### CODE REVIEW

**Review by lrytz — APPROVED** [review]
👍 thank you!

**Comment by SethTisue** [comment]
@som-snytt `git bisect` fingers this PR for at least some of the failures at https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-jdk11-integrate-community-build/3646/console (scroll to bottom)

is it clear to you or Lukas what's going on? do we need to revert this for 2.13.9?

**Comment by SethTisue** [comment]
the finch and pascal failures have a different cause

the zinc failure is definitely this PR and minimizes to:

before:

```
scala 2.13.8> (Array(1), Array("foo")).zipped
                                       ^
              warning: method zipped in class Ops is deprecated (since 2.13.0): Use xs.lazyZip(ys)
val res0: scala.runtime.Tuple2Zipped[Int,scala.collection.mutable.ArraySeq[Int],String,scala.collection.mutable.ArraySeq[String]] = (ArraySeq(1), ArraySeq(foo)).zipped
```

after:

```
scala> (Array(1), Array("foo")).zipped
                                ^
       error: No implicit view available from Array[Int] => scala.collection.IterableOps[El1,Iterable,It1] with It1.
```

**Comment by som-snytt** [comment]
Thanks, I'll take a look.

**Comment by som-snytt** [comment]
Follow-up at https://github.com/scala/scala/pull/10018

I'm still glad I got number 9999.
