### PR TITLE
Add Predef.nothingArrayOps

### LINKED ISSUE #10590: `headOption` method does not compile for some `Array[Nothing]`
```
Welcome to Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_131).
Type in expressions for evaluation. Or try :help.

scala> Array.empty.headOption // OK
res0: Option[Nothing] = None

scala> val emptyArray = Array.empty
emptyArray: Array[Nothing] = Array()

scala> emptyArray.headOption // Does not compile
<console>:13: error: value headOption is not a member of Array[Nothing]
       emptyArray.headOption // Does not compile
                  ^
```

### PR DESCRIPTION
**Pull request by Atry**
This change should fix https://github.com/scala/bug/issues/10590

### CODE REVIEW

**Comment by Atry** [comment]
Is it possible move this PR to 2.13.0-RC2 milestone instead 2.13.1, since the bug fix is not forward compatible.

**Comment by Atry** [comment]
It seems that `Nothing` type appeared in `Predef` breaks scala reflect `ToolBox`...

**Comment by Atry** [comment]
@SethTisue This is a forward-incompatible change, and CI fails due to MiMa checks. Is it too late to be included in Scala 2.13?

**Comment by SethTisue** [comment]
@adriaanm is making the final calls, but I think it's not too late

**Comment by adriaanm** [comment]
I'd rather not mess with implicits in predef in RC2 unless there's a very compelling need, and an empty array of Nothing seems like enough of a corner case that I don't think we should risk throwing off the balance of our jenga tower of implicits.

**Comment by szeiger** [comment]
I agree. The code from the ticket already compiles in 2.13 (via `copyArrayToImmutableIndexedSeq`, which is as good as anything for a corner case that you should never hit in practice) and the underlying `Nothing` bug appears to be fixed in Dotty.

**Comment by szeiger** [comment]
As commented on the ticket, I think we should keep the current "fix" (via the deprecated implicit conversion) for 2.14 instead of adding another implicit conversion to the mix.

**Comment by SethTisue** [comment]
as per https://www.scala-lang.org/2019/12/18/road-to-scala-3.html , it's going to be a while before we can add anything to the 2.13/3.0 standard library
