### PR TITLE
SI-7916: ScriptEngine support

### PR DESCRIPTION
**Pull request by som-snytt**
Refactor the ScriptEngine support to an adaptor atop the
IMain API.

Allow references to resolve to context attributes. (The
attributes must be defined at compilation time, though
they may resolve to updated values at evaluation time.)

This means that attributes are not bound statically in
REPL history. In particular, we forgo the trick of binding
attributes named "name: Type" as typed values.

Instead, an `x` bound in dynamic context is injected into
the script as a dynamic selection `$ctx.x` where `ctx`
performs the look-up in the script context.

When a compiled script is re-evaluated, a new instance of
the script class is created and defined symbols are
rebound.

### CODE REVIEW

**Comment by som-snytt** [comment]
Maybe a useful separation of concerns.

File: test/junit/scala/tools/nsc/interpreter/ScriptedTest.scala [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+package interpreter
+
+import org.junit._, Assert._, runner.RunWith, runners.JUnit4
+
+@RunWith(classOf[JUnit4])
+class ScriptedTest {
+  import javax.script._
+  import scala.tools.nsc.interpreter.Scripted
+
+  //new ScriptEngineManager().getEngineByName("scala").asInstanceOf[ScriptEngine with Compilable]
```
Comment (lrytz) [inline test/junit/scala/tools/nsc/interpreter/ScriptedTest.scala]: what is the reason for having this commented line? is this method of getting the script engine tested somewhere else?

**Comment by lrytz** [comment]
This LGTM otherwise, but I'm not really familiar enough with JSR223

**Comment by retronym** [comment]
I think we should get this one in. It needs rebasing, though.

**Comment by som-snytt** [comment]
I'll have to get familiar enough with JSR223.

**Comment by som-snytt** [comment]
Added `setWriter` support to capture `Console.out`.

**Comment by lrytz** [comment]
The following problem manifests only when using sbt as explained; it works when building locally and running `build/pack/bin/scala`.

Take this `build.sbt` file:

```
resolvers += "Scala PR Validation Snapshots" at "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/"

scalaVersion := "2.12.0-8876c1d-SNAPSHOT"
```

and run `sbt console`. I get:

```
Welcome to Scala 2.12.0-8876c1d-SNAPSHOT (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_71).
Type in expressions for evaluation. Or try :help.

scala> import javax.script._; import scala.tools.nsc.interpreter.Scripted
import javax.script._
import scala.tools.nsc.interpreter.Scripted

scala> val m = new ScriptEngineManager()
m: javax.script.ScriptEngineManager = javax.script.ScriptEngineManager@7462718f

scala> m.registerEngineName("scala", new Scripted.Factory)

scala> val s = m.getEngineByName("scala").asInstanceOf[ScriptEngine with Compilable]
s: javax.script.ScriptEngine with javax.script.Compilable = scala.tools.nsc.interpreter.Scripted@7bd80c4b

scala> s.eval("1")
scala.reflect.internal.FatalError: package scala does not have a member Int
  at scala.reflect.internal.Definitions$DefinitionsClass.fatalMissingSymbol(Definitions.scala:1195)
  at scala.reflect.internal.Definitions$DefinitionsClass.scala$reflect$internal$Definitions$DefinitionsClass$$$anonfun$79(Definitions.scala:1218)
  at scala.reflect.internal.Definitions$DefinitionsClass.getMember(Definitions.scala:1213)
  at scala.reflect.internal.Definitions$ValueClassDefinitions$class.valueClassSymbol(Definitions.scala:78)
  at scala.reflect.internal.Definitions$ValueClassDefinitions$class.IntClass(Definitions.scala:119)
  at scala.reflect.internal.Definitions$DefinitionsClass.IntClass$lzycompute(Definitions.scala:158)
  at scala.reflect.internal.Definitions$DefinitionsClass.IntClass(Definitions.scala:158)
  at scala.reflect.internal.Definitions$ValueClassDefinitions$class.IntTpe(Definitions.scala:132)
  at scala.reflect.internal.Definitions$DefinitionsClass.IntTpe$lzycompute(Definitions.scala:158)
  at scala.reflect.internal.Definitions$DefinitionsClass.IntTpe(Definitions.scala:158)
  at scala.tools.nsc.symtab.classfile.ClassfileParser.sig2type$1(ClassfileParser.scala:630)
  at scala.tools.nsc.symtab.classfile.ClassfileParser.sig2type$1(ClassfileParser.scala:728)
  at scala.tools.nsc.symtab.classfile.ClassfileParser.scala$tools$nsc$symtab$classfile$ClassfileParser$$sigToType(ClassfileParser.scala:774)
  at scala.tools.nsc.symtab.classfile.ClassfileParser$ConstantPool.getType(ClassfileParser.scala:289)
  at scala.tools.nsc.symtab.classfile.ClassfileParser.parseMethod(ClassfileParser.scala:568)
  at scala.tools.nsc.symtab.classfile.ClassfileParser.scala$tools$nsc$symtab$classfile$ClassfileParser$$$anonfun$10(ClassfileParser.scala:483)
  at scala.tools.nsc.symtab.classfile.ClassfileParser.queueLoad$1(ClassfileParser.scala:483)
  at scala.tools.nsc.symtab.classfile.ClassfileParser.scala$tools$nsc$symtab$classfile$ClassfileParser$$$anonfun$11(ClassfileParser.scala:493)
  at scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:498)
  at scala.tools.nsc.symtab.classfile.ClassfileParser.scala$tools$nsc$symtab$classfile$ClassfileParser$$$anonfun$2(ClassfileParser.scala:150)
  at scala.tools.nsc.symtab.classfile.ClassfileParser.parse(ClassfileParser.scala:125)
  at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader.scala$tools$nsc$symtab$SymbolLoaders$ClassfileLoader$$$anonfun$13(SymbolLoaders.scala:347)
  at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader.doComplete(SymbolLoaders.scala:347)
  at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:211)
  at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1513)
  at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1658)
  at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1403)
  at scala.tools.nsc.Global$Run.<init>(Global.scala:1128)
  at scala.tools.nsc.interpreter.IMain._initialize(IMain.scala:120)
  at scala.tools.nsc.interpreter.IMain.global$lzycompute(IMain.scala:149)
  at scala.tools.nsc.interpreter.IMain.global(IMain.scala:148)
  at scala.tools.nsc.interpreter.IMain$naming$.<init>(IMain.scala:177)
  at scala.tools.nsc.interpreter.IMain.naming$lzycompute(IMain.scala:176)
  at scala.tools.nsc.interpreter.IMain.naming(IMain.scala:176)
  at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.<init>(IMain.scala:676)
  at scala.tools.nsc.interpreter.IMain.bind(IMain.scala:607)
  at scala.tools.nsc.interpreter.IMain.bind(IMain.scala:647)
  at scala.tools.nsc.interpreter.IMain.scala$tools$nsc$interpreter$IMain$$$anonfun$59(IMain.scala:646)
  at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:202)
  at scala.tools.nsc.interpreter.IMain.quietBind(IMain.scala:646)
  at scala.tools.nsc.interpreter.Scripted.compile(Scripted.scala:95)
  at scala.tools.nsc.interpreter.Scripted.eval(Scripted.scala:129)
  at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
```

**Comment by lrytz** [comment]
(the scala library is not on the compilation classpath, i'm trying to figure out why)

**Comment by lrytz** [comment]
I guess it's that [`usejavacp`](https://github.com/scala/scala/commit/8876c1d715a155f62acacdb2546e767a9714a2fb#diff-2e08cb484e073265182aba693de67ebfR256) doesn't work; I set a breakpoint when initializing the compiler classpath and checked `System.getProperty("java.class.path")`: got `/Users/luc/.sbt/launchers/0.13.9/sbt-launch.jar`. Ideas how a good classpath / settings could be obtained?

Anyway, this problem seems unrelated to the changes in this PR.

**Comment by lrytz** [comment]
I'm still lacking JSR223 familiarization, but to me this PR looks very good. It could maybe get a little more testing. Here's some log of my playground

```
Welcome to Scala 2.12.0-20160201-221940-8876c1d715 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_71).
Type in expressions for evaluation. Or try :help.

scala> import javax.script._; import scala.tools.nsc.interpreter.Scripted
import javax.script._
import scala.tools.nsc.interpreter.Scripted

scala> val m = new ScriptEngineManager()
m: javax.script.ScriptEngineManager = javax.script.ScriptEngineManager@5e17553a

scala> m.registerEngineName("scala", new Scripted.Factory)

scala> val s = m.getEngineByName("scala").asInstanceOf[ScriptEngine with Compilable]
s: javax.script.ScriptEngine with javax.script.Compilable = scala.tools.nsc.interpreter.Scripted@726e5805

scala> s.eval("1")
res1: Object = 1

scala>

scala> s.eval("$ctx.foo") // DynamicContext
res2: Object = null

scala> s.eval("$ctx.foo = BigInt(12)")
res3: Object = 12

scala> s.eval("$ctx.foo")
res4: Object = 12

scala> s.eval("foo")
res5: Object = 12

scala>

scala> s.eval("$ctx.bar")
res6: Object = null

scala> s.eval("bar")
<console>:12: error: not found: value bar
       bar
       ^
javax.script.ScriptException: compile-time error
  at scala.tools.nsc.interpreter.Scripted.scala$tools$nsc$interpreter$Scripted$$$anonfun$7(Scripted.scala:111)
  at scala.tools.nsc.interpreter.Scripted$DynamicContext.apply(Scripted.scala:38)
  at scala.tools.nsc.interpreter.Scripted.compile(Scripted.scala:99)
  at scala.tools.nsc.interpreter.Scripted.eval(Scripted.scala:129)
  at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
  ... 30 elided

scala> s.put("bar", 1)

scala> s.eval("$ctx.bar")
res9: Object = 1

scala> s.eval("$ctx.bar = Int.box(23)")
res10: Object = 23

scala> s.eval("$ctx.bar")
res11: Object = 23

scala> s.eval("bar")
res12: Object = 23

scala>

scala> s.eval("baz")
<console>:12: error: not found: value baz
       baz
       ^
javax.script.ScriptException: compile-time error
  at scala.tools.nsc.interpreter.Scripted.scala$tools$nsc$interpreter$Scripted$$$anonfun$7(Scripted.scala:111)
  at scala.tools.nsc.interpreter.Scripted$DynamicContext.apply(Scripted.scala:38)
  at scala.tools.nsc.interpreter.Scripted.compile(Scripted.scala:99)
  at scala.tools.nsc.interpreter.Scripted.eval(Scripted.scala:129)
  at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
  ... 30 elided

scala> s.eval("val baz = -1")
res14: Object = -1

scala> s.eval("baz")
res15: Object = -1

scala> s.eval("$ctx.baz") // still null
res16: Object = null

scala> s.eval("$ctx.baz = Int.box(-2)")
res17: Object = -2

scala> s.eval("baz")
res18: Object = -2

scala> s.eval("$ctx.baz")
res19: Object = -2

scala> s.eval("baz = Int.box(-3)")
res20: Object = -3
```

**Comment by lrytz** [comment]
@rjolly would you be interested to also review this PR?

File: src/repl/scala/tools/nsc/interpreter/Scripted.scala [hunk 2]
```diff
@@ -0,0 +1,292 @@
...
+  /* All scripts are compiled. The supplied context defines what references
+   * not in REPL history are allowed, though a different context may be
+   * supplied for evaluation of a compiled script.
+   */
+  def compile(script: String, context: ScriptContext): CompiledScript = {
+    // TODO a mechanism for post-init actions
+    if (!bound) {
+      //intp quietBind ("engine" -> this.asInstanceOf[ScriptEngine])
+      //intp quietBind NamedParam[DynamicContext]("$ctx", dynamicContext)
+      intp quietBind NamedParamClass(intp.ctx, "scala.tools.nsc.interpreter.Scripted#DynamicContext", dynamicContext)
```
Comment (rjolly) [inline src/repl/scala/tools/nsc/interpreter/Scripted.scala]: Regarding the line below, what I intended was to make the interpreter available as a ScriptEngine, that is, it should be "this" and not "intp" (and the name was "engine", without $, it would be cool if it could remain like this).

File: src/repl/scala/tools/nsc/interpreter/Scripted.scala [hunk 3]
```diff
@@ -0,0 +1,292 @@
...
+      intp quietBind NamedParam[IMain]("$intp", intp)(StdReplTags.tagOfIMain, classTag[IMain])
```
Comment (rjolly) [inline src/repl/scala/tools/nsc/interpreter/Scripted.scala]: Regarding this line, what I intended was to make the interpreter available as a ScriptEngine, that is, it should be "this" and not "intp" (and the name was "engine", without $, it would be cool if it could remain like this). Otherwise, LGTM.

File: src/repl/scala/tools/nsc/interpreter/IMain.scala [hunk 4]
```diff
@@ -1046,31 +986,6 @@ class IMain(@BeanProperty val factory: ScriptEngineFactory, initialSettings: Set
...
 
-  def createBindings: Bindings = new IBindings {
-    override def put(name: String, value: Object): Object = {
-      val n = name.indexOf(":")
-      val p: NamedParam = if (n < 0) (name, value) else {
-        val nme = name.substring(0, n).trim
-        val tpe = name.substring(n + 1).trim
-        NamedParamClass(nme, tpe, value)
-      }
-      if (!p.name.startsWith("javax.script")) bind(p)
```
Comment (rjolly) [inline src/repl/scala/tools/nsc/interpreter/IMain.scala:1057]: Also, this line was intended to avoid the binding by jrunscript of variables with names invalid in scala ("javax.script.x"). Hence it would be interesting to test the new engine with jrunscript, as the problem may still exist.

**Comment by som-snytt** [comment]
This is proof-of-concept; I don't know what the use cases are, for interoperating with Objects; and I haven't exercised it much, for the usual reasons of ignorance and laziness, and not knowing if it's useful to pursue. Suggestions welcome.

@rjolly Am I right that you can usually throw weird names in backticks? The REPL isn't currently as backtick-friendly as it ought to be.

**Comment by rjolly** [comment]
@som-snytt I tested it, and it seems my two concerns above are solved on the Java side. For one thing, jrunscript does not bind long names like javax.script.filename and javax.script.argv anymore. Now it binds an "arguments" variable, and also "engine" with the ScriptEngine, which solves my first issue.

**Comment by rjolly** [comment]
There is one more caveat, still related to binding variables. With your new scheme, one needs to jarlist not only scala-library.jar, but also scala-compiler.jar and scala-reflect.jar too (as the former depends on it). If not done, one gets (using 2.12.0-8876c1d-SNAPSHOT):

```
jarlister scala-library.jar
jrunscript -classpath scala-compiler.jar:scala-reflect.jar:scala-library.jar -l scala
scala> "hello world"
<console>:5: error: object tools is not a member of package scala
  var value: scala.tools.nsc.interpreter.Scripted#DynamicContext = _
                   ^
<console>:6: error: object tools is not a member of package scala
  def set(x: Any) = value = x.asInstanceOf[scala.tools.nsc.interpreter.Scripted#DynamicContext]
                                                 ^
<console>:5: error: object tools is not a member of package scala
  var value: scala.tools.nsc.interpreter.IMain = _
                   ^
<console>:6: error: object tools is not a member of package scala
  def set(x: Any) = value = x.asInstanceOf[scala.tools.nsc.interpreter.IMain]
                                                 ^
hello world
scala>
```

The problem is caused by these lines:

```
intp quietBind NamedParamClass(intp.ctx, "scala.tools.nsc.interpreter.Scripted#DynamicContext", dynamicContext)
intp quietBind NamedParam[IMain]("$intp", intp)(StdReplTags.tagOfIMain, classTag[IMain])
```

, which go through the following statement:

```
bindRep.compile("""
    |object %s {
    |  var value: %s = _
    |  def set(x: Any) = value = x.asInstanceOf[%s]
    |}
  """.stripMargin.format(bindRep.evalName, boundType, boundType)
```

, causing the errors. Formerly the problem was avoided by casting the interpreter to javax.script.ScriptEngine, which is known outside of scala-compiler.jar . To solve it in the present construct, we could define an interface for DynamicContext , which we would put in scala-library.jar . And again regarding IMain, we should not bind it, but instead "this" (the Scripted instance) as instance of ScriptEngine (or nothing at all, as jrunscript is taking care of it, as seen above).

**Comment by MaggieLeber** [comment]
I'm trying to resurrect a year-old branch of our project to see if I can get this to work for us.  Our use case is a bit twisty; We have a Play Framework 2.3 application that embeds a Java library that supports JSR-223 script engines...and I need to have the automated tests operate under `sbt testOnly` of course. I have hacked the Java library (and its classpath) sufficiently to get past the classic `package scala does not have a member Int` and `scala.reflect.internal.FatalError: class StringContext does not have a member f` junk. 

`java.lang.NoSuchMethodError: scala.tools.nsc.interpreter.IMain$.defaultOut()Lscala/tools/nsc/NewLinePrintWriter;` is currently happening when I try to `print` or occasionally even with `System.out.println` (This may be caused by having 2.12 on the classpath for the Java library while still being on 2.11 for the enclosing Play app...I tried moving the app forward but my Scala dependencies at that level had a conniption, 

I'm also kind of stumbling around as to how I reference stuff in the script context. `$ctx` doesn't _appear_ to be defined, but I may have to dig back into the hacked Java lib and make sure the context is properly set there; I may have broken it trying to get it to work on Scala 2.11, before it was even supported.  

Are my comments about my floundering best made here, or back on SI-7916? @Lukas Rytz invited me to pop in here and contribute, and kindly provided a 2.12 build with this on it.

**Comment by som-snytt** [comment]
Thanks @rjolly and @MaggieLeber , I'll make time to push it forward. This is the right place to comment on this implementation.

I guess they don't require a SIP or SLIP, or a RIP (repl improvement). I kind of which there were a RIP.

**Comment by MaggieLeber** [comment]
I don't have this working yet in my use case. I think I need to do a cut-down exemplar without Play 2.3 and all the myriad dependencies of our app, most of whom don't to yet have 2.12 binaries available. 

I'm still unclear how I refer to values in the passed `ScriptContext` from within the Scala script; `$ctx` doesn't seem to be working; it gets a compile error, but I'm not absolutely certain I've got the classpath built correctly in my hack on the Java library. 

```
    if (SCALA_SCRIPTING_LANGUAGE.equals(language)) {
        String compilerPath;
        String libPath;
        String thisPath;
        try {
            compilerPath = java.lang.Class.forName("scala.tools.nsc.Interpreter").getProtectionDomain().getCodeSource().getLocation().getPath();
            libPath = java.lang.Class.forName("scala.Some").getProtectionDomain().getCodeSource().getLocation().getPath();
            Class someClass = java.lang.Class.forName("scala.Some");
            ((IMain)scriptEngine).settings().embeddedDefaults(this.getClass().getClassLoader());
        } catch (Exception e) {
            throw new RuntimeException("classpaths boogered", e);
        }
       // ((MutableSettings.BooleanSetting)(((IMain)scriptEngine).settings().usejavacp())).value_$eq(true);
        ((MutableSettings.BooleanSetting)(((IMain)scriptEngine).settings().usemanifestcp())).value_$eq(true);
        ((MutableSettings.PathSetting)(((IMain)scriptEngine).settings().bootclasspath())).append(compilerPath+libPath);
        (((IMain)scriptEngine).settings().classpath()).append(compilerPath+libPath);
    }
}        
```

My use case looks like this:

image

**Comment by MaggieLeber** [comment]
OK, gave up on sorting that mess; it's too complicated. So now I'm trying to run Scala scripts in jMeter as JSR223 samplers. 

jMeter finds the `ScriptEngine` OK, but items placed in the `ScriptContext` by the host seem to get their type erased all the way back to `Object` when you try to access their members. 

image

```
<console>:13: error: value info is not a member of Object
       def logit(s : String) = $ctx.log.info
```

Although if you sneak up on it you can catch it:
image

`Error` ends up being a handy bottle to put messages in because I have no clue where `println` is going and I don't seem to be able to get to the Logger or `OUT` yet. 

Update: Progress! 
image

Update: it works if you restore the erased type info!!!:

```
val out = ($ctx.context.getAttribute("OUT")).asInstanceOf[java.io.PrintStream]
out.println("foo for reals")
```

image

**Comment by som-snytt** [comment]
@MaggieLeber Yes, currently all you get is an `Object` unless you cast. Example https://github.com/som-snytt/scala/blob/issue/7916-ScriptEngine-deferred/test/junit/scala/tools/nsc/interpreter/ScriptedTest.scala#L21

Previously, it took apart the bound name as a `name: Type` pair and that's how it was statically "registered" in REPL history. There's no script API to say directly "bind as this type in the target environment."

One could hijack the API with the colon trick, or add a method that includes type info.

**Comment by MaggieLeber** [comment]
Unfortunately, I think any approach that erases type information in the objects in a ScriptContext is in for a very rough ride from folks approaching Scala as a JSR223 implemention. It's common for a JSR223 host to chain script executions, sharing their contexts between executions which may occur under different ScriptEngines. Activiti and jMeter are good examples. That said, I suppose it's better than not working at all.

**Comment by SethTisue** [comment]
> any approach that erases type information in the objects in a ScriptContext is in for a very rough ride from folks approaching Scala as a JSR223 implemention

isn't this an inherent issue with JSR223 itself, rather than a shortcoming of our implementation in particular? (or am I confused?)

**Comment by som-snytt** [comment]
One option is to wrap bound objects in `Dynamic`. It's dynamic all the way down... I didn't have a chance to look at it yet.

**Comment by MaggieLeber** [comment]
@SethTisue Other JSR233 implementations expose the objects in the `ScriptContext` with their type info intact.  Why would one expect it to be removed?

**Comment by som-snytt** [comment]
Given an object, we can only ascribe to it what we can learn through reflection. Maybe that's good enough. I'll try it out.

BTW, the idea is that you don't use `$ctx` in your script code. If you make a reference `x` and there's no `x` in your interpreter history but there is an `x` in the script context, that `x` is used (by some magic: the script is rewritten to include `def x = $ctx.x`).

**Comment by MaggieLeber** [comment]
Ah, OK. I'm kind of crippled up here because I have to drop my experiments into a run of jMeter and see what comes out; more often than not it's a compile failure with the error off in another window. 

I've been trying to get enough info about the context objects to fix their type correctly as @som-snytt suggests...and it's taking my brain on an interesting trip though Scala types. An educational journey indeed. 20 years of Java have made me a bit resistant to assimilating the idea that there is more to types than classes...but I can be trained, even at this late date. :-)  

I'd suspected that referring to $ctx might be unnecessary...

Indeed: 

```
val out = log.asInstanceOf[org.apache.log.Logger]
out.info("No more $ctx!")
```

works fine. A bit tidier. 

image

**Comment by SethTisue** [comment]
> Other JSR233 implementations expose the objects in the ScriptContext with their type info intact. Why would one expect it to be removed

@MaggieLeber Can you show a code sample or transcript or something that concretely demonstrates what you mean by that? I do not understand your claim.

**Comment by MaggieLeber** [comment]
@SethTisue  Sure. Let me rip some stuff out of our tests. 

This test builds a BPML process with a series of ScriptTasks. The body of Activiti ScriptTasks can be in any JSR223 language for which engines can be found on the classpath, so far we use Groovy and Javascript and we'd sure like to add Scala to the vocabulary. (Beanshell and Python are other conceivable candidates, but there's such a thing as "too much polyglot".)

I'll paste the scripts here as they're constructed in Scala strings; they're eventually wired up into a big BPML document that the Activiti engine eventually accepts as an executable deployment.

The first one is in Nashorn-flavored Javascript and sets a bunch of execution variables into the ScriptContext (referred to here as `execution`.

```
      val lotsOfVarsNashorn =   // convenience test data of various Javascript types
        """
          |      load("nashorn:mozilla_compat.js");
          |      importPackage(java.lang);
          |      importPackage(java.util);
          |      execution.setVariable("floaty", 3.14159265359);
          |      execution.setVariable("anInteger", 10);
          |      execution.setVariable("aString", "foo");
          |      execution.setVariable("thisIsNull", null);
          |      execution.setVariable("thisIsTrue", true);
          |      execution.setVariable("thisIsFalse", false);
          |      var userMap = new HashMap();
          |      userMap.put("item1", 100);
          |      userMap.put("item2", 200.00);
          |      userMap.put("item3", "this is item3");
          |      var subMap= new HashMap();
          |      subMap.put("item1", 100);
          |      subMap.put("item2", 200.00);
          |      subMap.put("item3", "this is item3");
          |      userMap.put(wf_currentAssignee, "This is my email: " + wf_currentAssignee);
          |      userMap.put("subMap", subMap);
          |      execution.setVariable("userMap", userMap);
          |      var myArray = new ArrayList();
          |      myArray.add("text1");
          |      myArray.add(2.0);
          |      myArray.add(null);
          |      myArray.add(true);
          |      myArray.add(false);
          |      myArray.add(4);
          |      var mySubArray = new ArrayList();
          |      mySubArray.add(null);
          |      mySubArray.add(true);
          |      mySubArray.add(false);
          |      mySubArray.add(4);
          |      myArray.add(mySubArray);
          |      execution.setVariable("myArray",myArray);
        """.stripMargin
```

The next step is a Groovy script that pulls the vars out of his ScriptContext and logs into a web service to write them as JSON into a MongoDB database. The resulting MongoDB document key is put into the context for subsequent tasks  in the process to pick up for later processing. 

In real-world use these two steps might be widely separated in time; the values are serialized and persisted externally in the meantime and then restored to a context for the next script when it is scheduled. Here again the script context is access through `execution`: 

```
      val objectstoreWrite = // Here's a Groovy script template using a Scala string interpolator
      // $$ => $, $var gets a substitution for the value of "var"
        s"""
           |package processes.scripts
           |import groovyx.net.http.HTTPBuilder
           |import groovy.json.*
           |import scala.collection.*
           |
           |//TODO: this hostname:port will only work in testing with ServerSuiteConfig
           |def pointflow = new HTTPBuilder( 'http://localhost:19001/' )
           |
           |// login to Pointflow
           |String sessionKey;
           |String osKey;
           |pointflow.post(
           |   path: 'auth',
           |   query: [email:'$TEST_USER_ID', password:'$TEST_USER_PWD', apikey:'$TEST_USER_APIKEY']
           |   )
           |{ resp, authResp ->
           |    execution.log.info("login status: $$resp.status session key: $${authResp.RESULT.SESSIONKEY}")
           |    sessionKey = authResp.RESULT.SESSIONKEY
           |}
           |
           |// write something to ObjectStore, pick out the vars you want
           |// and wrap them in an object called "foo"
           |pointflow.post( path: 'objectstore',
           |                query: [Authorization:sessionKey],
           |                contentType: 'application/json',
           |                requestContentType: 'application/json',
           |                body: JsonOutput.toJson(
           |                  [foo: [
           |                  easyTimestamp : new Date().toString(),
           |                  floaty:  execution.getVariable('floaty'),
           |                  astring: execution.getVariable('aString')+"bar",
           |                  usermap: execution.getVariable('userMap'),
           |                  scalalist: scala.collection.JavaConversions.asScalaBuffer(["apples","peaches","pumpkin"]).toList()
           |                  ]]
           |                  )
           |                )
           |  { resp, json ->
           |    execution.log.info("Objectstore post Status: $$resp.status response: $$json")
           |    osKey = json.RESPONSE.objId
           |    execution.log.info("Objectstore key: $$osKey")
           |    execution.setVariable("objectstoreKey",osKey)
           |  }
           |        """.stripMargin
```

Note that neither the JS that created them nor the Groovy that read them back needed to fuss about , declare or coerce the type or class of these values; they hadn't all been mysteriously erased back to Object.

Does that help? I realize that we have widely different points of view here, but in my experience this is a typical JSR223 use case. 

 It may just be that the JSR223 implementations I'm familiar with are pretty loose about typing to the point of duck-ness, whereas Scala is type-strict 24/7. These may be seriously conflicting goals. 

Ultimately one may have to do a type-declarative introduction to any value in the context before using it in Scala code.

**Comment by SethTisue** [comment]
thanks for the detailed answer, this is helpful.

> neither the JS that created them nor the Groovy that read them back needed to fuss about , declare or coerce the type or class of these values; they hadn't all been mysteriously erased back to Object

JS and Groovy are dynamically typed languages; so everything is always just Object to them anyway. It's only statically typed languages like Scala where the concept of needing to have a more specific compile-time type for something even arises.

or in other words:

> It may just be that the JSR223 implementations I'm familiar with are pretty loose about typing to the point of duck-ness, whereas Scala is type-strict 24/7. These may be seriously conflicting goals.

yes, precisely!

I think it's simply normal and expected in both Scala and Java to have to typecast everything you get back from `eval` and `getAttribute`.

the alternative that Som mentions of using `Dynamic` instead is interesting. I haven't thought too deeply about it, but that might be suitable for some use cases. but in bare JSR223, the return types are `Object`, not `Dynamic`, so moving things into `Dynamic` would have to be the job of some kind of additional layer or wrapper.

**Comment by MaggieLeber** [comment]
Yeah, it's tantalizing...when I see I can do `thing.getClass` the urge to automatically feed that to `asInstanceOf` somehow is overwhelming... but in fact thinking about it carefully, I'd need a time machine. 

Or use reflection somehow, which is what Som is looking at. 

I've been so heads-down into the day-to-day, it's hard to keep up with the new stuff in the language like `Dynamic` (It is new, isn't it? Tell me it's new...). Taking a few days out of work to attend the Typelevel shindig and NEScala in Philly next week may help me catch up.

**Comment by MaggieLeber** [comment]
I went back and ran the same jMeter setup against 2.12.0 M3 and got the familiar

```
2016/02/23 10:03:51 ERROR - jmeter.threads.JMeterThread: Error while processing sampler 'JSR223 Sampler' : scala.reflect.internal.MissingRequirementError: object scala in compiler mirror not found.
```

...so even as this stands, this change makes things much, much better. Me likey,  

@SethTisue has made me see the light about why this must work the way it does, so thanks for his patience on that.

**Comment by lrytz** [comment]
It sounds like this PR could be merged now, or are there still open questions / items?

**Comment by MaggieLeber** [comment]
Not from me. :+1: :shipit:

**Comment by rjolly** [comment]
I strongly advise that my comment of Feb 19 be followed, namely define an interface for DynamicContext and put it (somewhere) in scala-library.jar , so as to remove scripted code dependency to scala-compiler.jar (which I carefully managed to ensure in my original implementation). Otherwise, one has to jarlist scala-compiler.jar and scala-reflect.jar in addition to scala-library.jar , which is already painful enough.

And remove the binding of $intp as instance of IMain, for the same reason. This one is easy, the other one harder, please let me know if I can help by making a PR to @som-snytt 's repository.

**Comment by som-snytt** [comment]
It'll take me a bit to spin up on this issue again. I'd forgotten @rjolly 's previous comment about interfaces; and I vaguely remember there's a need to do something more Dynamic with objects in the context.

**Comment by som-snytt** [comment]
> But wait, there's more! It's a compiler _and_ a templating engine!

http://stackoverflow.com/a/36657794/1296806

**Comment by som-snytt** [comment]
I wanted to spend a couple of hours on this but hit a snag. Testing with a bad ref, it throws as shown:

https://gist.github.com/som-snytt/361d43d2c78e31364cc6d558e22f0638

I'll push and maybe @lrytz will hint at something.

For @rjolly hint, it pre-compiles a wrapper for the current context and also the dynamic adapter (which isn't strictly required).

**Comment by lrytz** [comment]
I'll take a look if I can reproduce - `ErrorType` should not make it to the backend.

**Comment by som-snytt** [comment]
I just noticed that adding the `reporter` override induces the exception. How is that possible? D'oh, I guess it's because the compiler relies on the reporter correctly reporting error state to halt compilation.

I'm distracted b/c heading to my day job and didn't intend to spend hours on this. But it makes me appreciate what FOSS means as a commitment. Actually I wanted to finish my dotty repl last weekend. :(

**Comment by lrytz** [comment]
> compiler relies on the reporter correctly reporting error state to halt compilation

right, it's actually the main loop that moves compiler phases forward: https://github.com/scala/scala/blob/2.12.x/src/compiler/scala/tools/nsc/Global.scala#L1480

> it makes me appreciate what FOSS means as a commitment. Actually I wanted to finish my dotty repl last weekend. :(

your commitment is quite unique! feel free to put your efforts where your motivation drags you. but this one will be worth pushing through!

**Comment by som-snytt** [comment]
So a compile error will throw:

```
javax.script.ScriptException: not found: value fooz in fooz at line number 12 at column number 8
```

I always doubt if the position is useful...

**Comment by som-snytt** [comment]
I encountered the wontfix where

```
[quick.repl] /home/apm/projects/snytt/src/repl/scala/tools/nsc/interpreter/Scripted.scala:45: error: not found: value valname_
[quick.repl]                 def `$valname_=`(x: Object) = $ctx.`$valname` = x"""
```

**Comment by lrytz** [comment]
ah, you mean https://github.com/scala/scala/pull/4663?

maybe when you're on this one next time, a rebase on current 2.12.x would be useful and unblock CI validation (assuming we manage to unblock CI itself – https://gitter.im/scala/contributors?at=5715ffbd4c2125fc3f03a200)

**Comment by som-snytt** [comment]
This was already rebased, but I haven't looked at squashing yet. In case I wanted to back something out; but probably I'll just move forward. The other desirable was to handle bound objects more dynamically. I think implicit conversion to Dynamic is not supported? That would have made falling back to reflective access easy.

**Comment by som-snytt** [comment]
Is this that old problem where spiders would poke an abort link?

```
  [partest] ok 1047 - run/WeakHashSetTest.scala               
Build was aborted
Aborted by anonymous
```

**Comment by szeiger** [comment]
If my assessment of this long thread is accurate, everyone's requests have been satisfied and all that remains is resolving the merge conflicts that have crept in. Are there any objections against merging the current state?

**Comment by lrytz** [comment]
yes, i think so too

**Comment by som-snytt** [comment]
I'll rebase. I think there is a future opportunity for improving the user experience of working with dynamically bound objects, but not a blocker for this PR.

**Comment by rjolly** [comment]
No objection.
