### PR TITLE
Avoid spurious shadowed import warning

### LINKED ISSUE #8121: Inconsistent handling of shadowed imported name
Create the following source files:

A.scala:
  package a
  object Foo

B.scala:
  package b
  import a.Foo
  class Foo

Then run 

scalac -d ./classes A.scala B.scala

The compilation succeeds.

But if I compile A and B separately:

scalac -d ./classes1 A.scala 
scalac -d ./classes2 -cp ./classes1 B.scala

I get "warning: imported `Foo' is permanently hidden by definition of class Foo in package b".

I also get this error if I replace "object Foo" with "class Foo" in A.scala. 

I guess this is supposed to succeed, since objects are values, not types, and so live in a different namespaces? But in that case it should also succeed when the files are compiled separately.

### PR DESCRIPTION
**Pull request by lrytz**
Use `!sym.exists` instead of `!= NoSymbol`. The compiler generates a
`ClassSymbol` when it sees `Foo.class`, but that symbol then doesn't
exist if `Foo` is only an `object` without companion class (`Foo.class`
is the mirror class with static forwarders for Java interop).

Fixes https://github.com/scala/bug/issues/8121

There might be a risk of this PR causing cyclic references because symbols are completed earlier.

### CODE REVIEW

File: src/library/scala/annotation/migration.scala [hunk 1]
```diff
@@ -27,4 +27,4 @@ package scala.annotation
  * @param changedIn The version, in which the behaviour change was
  * introduced.
  */
- private[scala] final class migration(message: String, changedIn: String) extends scala.annotation.StaticAnnotation
+private[scala] final class migration(message: String, changedIn: String) extends scala.annotation.StaticAnnotation
```
Comment (som-snytt) [inline src/library/scala/annotation/migration.scala:30]: Exceptional scouting!

File: test/files/neg/t11607.check [hunk 2]
```diff
@@ -1,4 +1,4 @@
-t11607.scala:2: error: class migration in package annotation cannot be accessed as a member of package annotation from package <empty>
+t11607.scala:2: error: not found: type migration
```
Comment (som-snytt) [inline test/files/neg/t11607.check:1]: Compiler could use githubesque, "We went looking for that symbol everywhere but couldn't find it."

File: src/compiler/scala/tools/nsc/typechecker/Namers.scala [hunk 3]
```diff
@@ -561,9 +561,9 @@ trait Namers extends MethodSynthesis {
           }
         }
         if (!tree.symbol.isSynthetic && expr.symbol != null && !expr.symbol.isInterpreterWrapper) {
-          if (base.member(from) != NoSymbol)
+          if (base.member(from).exists)
             check(to0)
-          if (base.member(from.toTypeName) != NoSymbol)
+          if (base.member(from.toTypeName).exists)
```
Comment (som-snytt) [inline src/compiler/scala/tools/nsc/typechecker/Namers.scala:566]: That's interesting, I always wonder about when it's OK to check exists. I have doubts about this "permanently hidden" check, which in the past was incorrect (for some case). The comment says "warn proactively", but there's no reason to be eager (though maybe there was in the past). An unused import is just an unused import; maybe an unused import of an implicit element should warn even if the lint is not enabled. Also ensure the warning is issued despite errors (due to missing implicits).

Other than deleting this check, maybe it's not terrible to force more, for the sake of more correctness.

**Review by som-snytt — APPROVED** [review]
Finishing the review if github keeps working a minute more. Approval with proviso that I'll look into the deletion option.

**Comment by som-snytt** [comment]
I wonder if this will receive the community treatment (after the community build manager recovers from Bernie Sanders).
