### PR TITLE
Avoid spurious "illegal trait super target" error

### LINKED ISSUE #12520: Weird Scala 2.13 Error: illegal trait super target found for method
## reproduction steps

using Scala 2.13.7,

```scala
class Outcome
trait TestSuite { thisTestSuite =>
  protected trait NoArgTest extends (() => Outcome)
  protected def withFixture(test: NoArgTest): Outcome = {
    test()
  }
}
trait TestSuiteMixin { this: TestSuite =>
  protected def withFixture(test: NoArgTest): Outcome
}
trait TimeLimitedTests extends TestSuiteMixin { this: TestSuite =>
  abstract override def withFixture(test: NoArgTest): Outcome = super.withFixture(test)
}
trait AnyFunSuiteLike extends TestSuite { thisSuite => }
abstract class Test[C] extends AnyFunSuiteLike with TimeLimitedTests
```

## problem

It got the following compiler error when compiles with Scala 2.13: 

```
cheeseng@cheeseng-RAVEN:~/git/213-bug$ scalac Test.scala
Test.scala:15: error: illegal trait super target found for method withFixture required by trait TimeLimitedTests;
 found   : protected def withFixture: ((test: _1.NoArgTest): Outcome) forSome { val _1: [C]Test[C] } in trait TestSuite;
 expected: protected def withFixture: ((test: _1.NoArgTest): Outcome) forSome { val _1: [C]Test[C] } in trait TestSuiteMixin
abstract class Test[C] extends AnyFunSuiteLike with TimeLimitedTests
```

The same code compiles fine with Scala 3 and 2.12.

This is originally reported as ScalaTest issue here: https://github.com/scalatest/scalatest/issues/2088

### PR DESCRIPTION
**Pull request by joroKr21**
Time travelling is a risky venture

Fixes scala/bug#12520

Follow-up for https://github.com/scala/scala/pull/7641

### CODE REVIEW

**Review by SethTisue — APPROVED** [review]
(but not merging right away in case someone who knows this stuff better wants to take a look)
