### PR TITLE
Fix override checks involving raw Java types

### LINKED ISSUE #11584: Cannot extend JavaFX class DatePickerSkin
Attaching a tar file of sample project. Simple run 'sbt compile' to see the error. I don't see any workaround for this problem.

Code works in 2.12.8 but not 2.13.0

[bug.zip](https://github.com/scala/bug/files/3321722/bug.zip)

Error is:

```
[error] /Users/curtis/guild1/code/bug/src/main/scala/Bug.scala:4:7: incompatible type in overriding
[error] private[package skin] def getBehavior(): com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior[_] (defined in class ComboBoxBaseSkin)
[error]   with private[package skin] def getBehavior(): com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior (defined in class DatePickerSkin);
[error]  found   : ()com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior
[error]  required: ()com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior[_]
[error] class Bug(ymPicker: DatePicker) extends DatePickerSkin(ymPicker) {
[error]       ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

### LINKED ISSUE #11840: scalac 2.13.1 "incompatible type in overriding" subclassing Hadoop FileSystem that javac accepts
Hi all, long time listener, first time poster. I have an odd scalac 2.13.1 issue that's affecting Apache Spark's transition to 2.13 (https://issues.apache.org/jira/browse/SPARK-25075 -> https://issues.apache.org/jira/browse/SPARK-30132)

It occurs in scalac 2.13.1 but not 2.12.10. This occurs in Java 8. I didn't see an obvious open issue here, or easy answer from the gitter channel, but https://github.com/scala/bug/issues/11575 looks possibly related.

Consider this simple subclass of a Hadoop LocalFileSystem class:

```
object foo extends org.apache.hadoop.fs.LocalFileSystem {}
```

Compiled with scalac 2.13.1, I get:

```
$ scalac -cp ~/.m2/repository/org/apache/hadoop/hadoop-common/3.2.0/hadoop-common-3.2.0.jar foo.scala 
foo.scala:1: error: incompatible type in overriding
def appendFile(x$1: org.apache.hadoop.fs.Path): org.apache.hadoop.fs.FSDataOutputStreamBuilder[S,B] forSome { type S <: org.apache.hadoop.fs.FSDataOutputStream; type B <: org.apache.hadoop.fs.FSDataOutputStreamBuilder[S,B] } (defined in class FileSystem)
  with def appendFile(x$1: org.apache.hadoop.fs.Path): org.apache.hadoop.fs.FSDataOutputStreamBuilder (defined in class FilterFileSystem);
 found   : (x$1: org.apache.hadoop.fs.Path)org.apache.hadoop.fs.FSDataOutputStreamBuilder
 required: (x$1: org.apache.hadoop.fs.Path)org.apache.hadoop.fs.FSDataOutputStreamBuilder[S,B] forSome { type S <: org.apache.hadoop.fs.FSDataOutputStream; type B <: org.apache.hadoop.fs.FSDataOutputStreamBuilder[S,B] }
object foo extends org.apache.hadoop.fs.LocalFileSystem {}
       ^
```

This says that the compiled class hierarchy for this Hadoop class is invalid, though naturally, javac has accepted and compiled it. The definition in `FileSystem.java` in Hadoop 3.2.0:

```
  public FSDataOutputStreamBuilder appendFile(Path path) {
    return new FileSystemDataOutputStreamBuilder(this, path).append();
  }
```

The subtype `FilterFileSystem.java` has:

```
  public FSDataOutputStreamBuilder appendFile(Path path) {
    return new FileSystemDataOutputStreamBuilder(this, path).append();
  }
```

The signature is evidently identical. Now, `FSDataOutputStreamBuilder` does take two generic types, not specified here in the Hadoop source code. I kind of understand the error, that you can't say that the generic types in the overload are consistent. 

But is this something that scalac should reject?

### PR DESCRIPTION
**Pull request by smarter**
In particular, this fixes https://github.com/scala/bug/issues/11840 which is a blocker for getting Spark on Scala 2.13. Also fixes https://github.com/scala/bug/issues/11584.

### CODE REVIEW

**Review by lrytz — APPROVED** [review]
Thanks, @smarter!

**Comment by michelou** [comment]
@smarter Thanks !

**Comment by lrytz** [comment]
This is not correct, unfortunately. From https://github.com/scala/bug/issues/12380:

```java
package p;

public class J {
  public static class C {
    public Object m() { return new Object(); }
  }
  public interface I {
    public String m();
  }
}
```

```scala
object Test extends p.J.C with p.J.I {
  def main(args: Array[String]): Unit = {
    println((this: p.J.I).m.trim)
  }
}
```

compiles and runs with

```
java.lang.ClassCastException: java.lang.Object cannot be cast to java.lang.String
	at Test$.m(Test.scala:1)
```

We have to continue checking for missing overrides even if both methods are defined in Java. I'll take a look. Hopefully we can narrow down the "skip" for Java-defined methods to the checks if two overrides are valid (in types, accessibility, ...).

**Comment by smarter** [comment]
Indeed, I was also having second thoughts about that check recently but hadn't came up with a test case.
