### PR TITLE
Upgrade Dotty to 0.23.0-RC1

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]

**Comment by SethTisue** [comment]
```
[error] -- Error: /home/travis/build/scala/scala/src/library/scala/collection/immutable/List.scala:479:20 
[error] 479 |  private[this] def filterImpl(p: A => Boolean, isFlipped: Boolean): List[A] = {
[error]     |                    ^
[error]     |private method filterImpl cannot override method filterImpl in trait StrictOptimizedIterableOps
```

(only Travis-CI tests Dotty, not Jenkins)

**Comment by lrytz** [comment]
It looks like dotty is right here:

```
Welcome to Scala 2.13.1 (Java HotSpot(TM) 64-Bit GraalVM EE 19.2.1, Java 1.8.0_231).
Type in expressions for evaluation. Or try :help.

scala> class C { def f = 0 }
defined class C

scala> class D extends C { private[this] def f = 1 }
defined class D

scala> (new D).f
java.lang.IllegalAccessError: tried to access method D.f()I from class
  ... 28 elided
```

**Comment by lrytz** [comment]
For the record, having an `ACC_PRIVATE` method in bytecode with the same signature as an inherited one is not problematic per se.

The example above works with dotty 0.22 because it emits

```
INVOKEVIRTUAL C.f ()I
```

while scalac 2.13.1 emits

```
INVOKEVIRTUAL D.f ()I
```

Dotty 0.23 would also use `D` as receiver I think (https://github.com/lampepfl/dotty/pull/8499), however it emits a compile-time error (cannot override with weaker accessibility).

However, thinking about it, `private` and `private[this]` methods should probably not be considered as overridding, so dotty would be wrong too – I need to check the spec. For example, the following works correctly in dotty and scalac:

```
scala> class C { private def f = 0; def x = f }
scala> class D extends C { private def f = 1; def y = f }

scala> (new D).y + (new D).x + (new C).x
res4: Int = 1
```

cc @smarter

**Comment by smarter** [comment]
We have a fix for scala-library in our community build, see the last two commits of https://github.com/dotty-staging/scala/commits/fix-list

> For the record, having an ACC_PRIVATE method in bytecode with the same signature as an inherited one is not problematic per se.

It prevents javac from calling the inherited public method, so I'd say it's pretty problematic :).

```java
class Test {
  void main(String... args) {
    new D().f();
  }
}
```
```java
try/Test.java:3: error: f() has private access in D
    new D().f();
           ^
1 error
```

**Comment by lrytz** [comment]
Well, it works if you upcast, and javac produces working bytecode
```
    C d = new D();
    System.out.println(d.f());
```

**Comment by smarter** [comment]
Right, but we might as well disallow it since it's a usability problem from java and since the equivalent java code wouldn't compile.

**Comment by lrytz** [comment]
https://www.scala-lang.org/files/archive/spec/2.13/05-classes-and-objects.html#overriding

> A member 𝑀 of class 𝐶 that matches a non-private member 𝑀′ of a base class of 𝐶 is said to override that member

> the following restrictions on modifiers apply

> * 𝑀 must not be `private`

Probably that covers it, as the spec also says about `private[this]`

> the restrictions for unqualified `private` apply
