### PR TITLE
Revert "SI-1786 incorporate defined bounds in inference"

### PR DESCRIPTION
**Pull request by adriaanm**
Have to revert because the stricter bounds it inferred break e.g., slick.
Worse, the fix was compilation order-dependent.

There's a less invasive fix (SI-6169) that could be generalized
in `sharpenQuantifierBounds` (used in `skolemizeExistential`),
but I'd rather not mess with existentials at this point.

This reverts commit e28c3edda4dd405ed382227d2a688b799bf33c72.

Conflicts:
    src/compiler/scala/tools/nsc/typechecker/Typers.scala
    test/files/pos/t1786.scala

review by @retronym

### CODE REVIEW

**Comment by retronym** [comment]
LGTM (regrettably)

I don't think its fit to ship after the experience with Slick. In the end I had to put _more_ explicit bounds in to get things to line up. And through the process, things would compile incrementally but not holistically, etc.

I should have raised the issue earlier (I've been through the process of patching Slick twice now). The difference second time round was that I'd seen the Java approach which we didn't consider originally, and which seems immune to unstable behaviour.

There might even be a third way: could sharpen the declared bounds lazily, e.g. when they are first involved in a type relation?

Here's a test case distilled from Slick:

``` scala
trait ShapeLevel

object Fail {
  abstract class ProductNodeShape[Level <: ShapeLevel, C, M <: C, U <: C, P <: C] extends Shape[Level, M, U, P] {
    def copy(shapes: Seq[Shape[_, _, _, _]]): Shape[Level, _, _, _]
  }

  abstract class Shape[Level <: ShapeLevel, -Mixed_, Unpacked_, Packed_]

  final class TupleShape[Level <: ShapeLevel, M <: Product, U <: Product, P <: Product](val shapes: Shape[_, _, _, _]*) extends ProductNodeShape[Level, Product, M, U, P] {
    def copy(shapes: Seq[Shape[_, _, _, _]]): Shape[Level, _, _, _] = ???
  }

  trait ShapeLevel
}

object Ok {
  abstract class Shape[Level <: ShapeLevel, -Mixed_, Unpacked_, Packed_]

  abstract class ProductNodeShape[Level <: ShapeLevel, C, M <: C, U <: C, P <: C] extends Shape[Level, M, U, P] {
    def copy(shapes: Seq[Shape[_, _, _, _]]): Shape[Level, _, _, _]
  }

  final class TupleShape[Level <: ShapeLevel, M <: Product, U <: Product, P <: Product](val shapes: Shape[_, _, _, _]*) extends ProductNodeShape[Level, Product, M, U, P] {
    def copy(shapes: Seq[Shape[_, _, _, _]]): Shape[Level, _, _, _] = ???
  }
}
```

It compiles on 2.10.3, but only `Ok` compiles on 2.11. `Fail` results in:

```
sandbox/test.scala:10: error: class TupleShape needs to be abstract, since method copy in class ProductNodeShape of type (shapes: Seq[Fail.Shape[_, _, _, _]])Fail.Shape[Level, _, _, _] is not defined
(Note that Seq[Fail.Shape[_, _, _, _]] does not match Seq[Fail.Shape[_ <: Fail.ShapeLevel, _, _, _]]: their type parameters differ)
  final class TupleShape[Level <: ShapeLevel, M <: Product, U <: Product, P <: Product](val shapes: Shape[_, _, _, _]*) extends ProductNodeShape[Level, Product, M, U, P] {
              ^
```

/cc @paulp

**Comment by retronym** [comment]
Could you add this test case to the PR?

**Comment by retronym** [comment]
A compromise position might be to keep this in behind a `-Y`. If you know what you're doing, you might still want to benefit from inferring bounds from types in JARs, at the expense of playing whack-a-mole with your own code.

**Comment by adriaanm** [comment]
I think it would be more rewarding to put a more liberal SI-6169 behind a -Y flag. I checked an eager SI-6169 subsumes SI-1786, but only if you do it early enough that you risk running into cycles sometimes. There's probably a way to work around those.

**Comment by adriaanm** [comment]
done, also removed the stray pos/t1786
