### PR TITLE
Upgrade to sbt 1.4.x

### PR DESCRIPTION
**Pull request by eatkins**
Builds on #9200

~Not for merge until 1.4.0 final is out~

### CODE REVIEW

**Comment by SethTisue** [comment]
thank you! I was working on inferior versions of these changes, but yours are better. I'll close mine.

**Comment by SethTisue** [comment]
to be investigated:

```
[warn] there are 66 keys that are not used by any other settings/tasks:
...
```

**Comment by SethTisue** [comment]
> [warn] there are 66 keys that are not used by any other settings/tasks:

I added a commit that addresses this, but it feels like I was suppressing false positives — the settings are in fact used, it seems to me.

**Comment by som-snytt** [comment]
When my daughter skips piano practice `there are 88 keys that are not used`.

**Comment by SethTisue** [comment]
upgraded to 1.4.0-RC2. (I verified that tweaking `excludeLintKeys` here remains necessary in RC2. @eatkins shall I open an sbt ticket on that?)

**Comment by eatkins** [comment]
Yes, it would be good to open a ticket.

**Comment by SethTisue** [comment]
Ticket: haven't yet, but will.

On Travis, twice so far: "The job exceeded the maximum time limit for jobs, and has been terminated." (I just hit restart another time.)

Before merge, we'll want to do some kind of local test to make sure there we're not seeing more than a modest performance regression here.

**Comment by SethTisue** [comment]
> Yes, it would be good to open a ticket.

@eatkins I determined that only `scalaSource` is affected, but I was unable to reproduce the problem in a standalone project. Ours is a complicated/unusual build, so I don't think we need to worry about it.

File: build.sbt [hunk 1]
```diff
@@ -1692,6 +1691,8 @@ def findJar(files: Seq[Attributed[File]], dep: ModuleID): Option[Attributed[File
 whitesourceProduct               := "Lightbend Reactive Platform"
 whitesourceAggregateProjectName  := "scala-2.13-stable"
 whitesourceIgnoredScopes         := Vector("test", "scala-tool")
+// for some reason sbt 1.4 issues an unused-setting warning for this, I don't understand why
```
Comment (dwijnand) [inline build.sbt:1379]: There's an sbt/sbt issue for this one: the sbt linter doesn't understand the `.all`/ScopeFilter usage that sbt-whitesource makes use of.

File: build.sbt [hunk 2]
```diff
@@ -486,9 +486,8 @@ lazy val commonSettings = instanceSettings ++ clearSourceAndResourceDirectories
   Compile / unmanagedResourceDirectories += (ThisBuild / baseDirectory).value / "src" / thisProject.value.id,
   sourcesInBase := false,
   Compile / scalaSource := (Compile / sourceDirectory).value,
-  Compile / javaSource := (Compile / sourceDirectory).value,
-  // resources are stored along source files in our current layout
-  Compile / resourceDirectory := (Compile / sourceDirectory).value,
```
Comment (dwijnand) [inline build.sbt:142]: I'm more concerned about the silent impact of removing these for linting reasons.

Are we sure that CI (or yourself, manually) is good enough that dropping these two isn't dropping anything on the floor?  I'd rather opt the linter out, unless you're fairly confident.

File: build.sbt (hunk 1 above)
Comment (SethTisue) [reply build.sbt:1379]: @dwijnand I couldn't find the ticket, unless you mean  https://github.com/sbt/sbt/issues/5485 ?

File: build.sbt (hunk 2 above)
Comment (SethTisue) [reply build.sbt:142]: pleased to meet you, Cautious Dale! I'm better acquainted with your brother, Let’s-Just-Merge-It-and-See Dale, but I'm sure the three of us will get along just fine :-)

I admit to not being too worried about this change in particular, but actually you're right — this is a substantial version bump (1.3 -> 1.4, I mean), so it would be prudent to use `jardiff` on all the build products (by which I mean, the contents of `build/pack` after you do `dist/mkPack`) and see if any funny stuff turns up

and so I did that just now, and nothing turned up

File: build.sbt (hunk 1 above)
Comment (SethTisue) [reply build.sbt:1379]: I'm going to hit "resolve conservation" since it's not a blocker, but I'll still add the link in a comment, if you find it

**Comment by SethTisue** [comment]
personally I'd be comfortable seeing this merged now, but perhaps Cautious Dale will want to wait until after 2.13.4 is released

File: build.sbt (hunk 2 above)
Comment (dwijnand) [reply build.sbt:142]: Okie dokie, thank you!

**Comment by dwijnand** [comment]
> personally I'd be comfortable seeing this merged now, but perhaps Cautious Dale will want to wait until after 2.13.4 is released

Yeah, this doesn't affect the release and there isn't even a non-release reason for which this needs to be merged this week or next.

**Comment by dwijnand** [comment]
The diff is good, but to avoid mistakes I won't give it a green checkmark...

**Comment by SethTisue** [comment]
interesting

```
[error] 1 of 9 test tasks failed:
[error] - testJarSize
[error]   - root/testJarSize failed: The reflect jar is too big: 3721892 bytes.
```

also, curious that this _didn't_ fail Jenkins

**Comment by dwijnand** [comment]
Might be because Jenkins runs the commit, while Travis CI runs the merge commit.

**Comment by SethTisue** [comment]
anyway 1.4.1 has bugs in terminal handling, let's wait for 1.4.2

**Comment by SethTisue** [comment]
after updating this PR from 1.4.2 to 1.4.3, the build won't even load:

```
[info] loading project definition from /Users/tisue/scala.213/project
[info] compiling 24 Scala sources to /Users/tisue/scala.213/project/target/scala-2.12/sbt-1.0/classes ...
[error] /Users/tisue/scala.213/project/GenerateDocsData.scala:35:16: object tools is not a member of package scala
[error]   import scala.tools.nsc.Settings
[error]                ^
```

is this actually expected? @eatkins @eed3si9n @dwijnand

it seems like a progression, actually. I don't know why it would be expected for scala-compiler to be on the classpath for compiling the build definition

offhand, looking at the 1.4.3 notes, the only thing I see that vaguely seems potentially related is sbt/sbt#6085?

I was able to fix it with:

```diff
--- project/plugins.sbt
+++ project/plugins.sbt
@@ -20,6 +20,7 @@ buildInfoPackage := "scalabuild"
 addSbtPlugin("com.typesafe" % "sbt-mima-plugin" % "0.8.0")
 
 libraryDependencies ++= Seq(
+  "org.scala-lang" % "scala-compiler" % scalaVersion.value,
   "org.eclipse.jgit" % "org.eclipse.jgit" % "4.6.0.201612231935-r",
```

which is fine actually, but I'm at least mildly curious why this changed.

(anyway `GenerateDocsData` doesn't even do the right thing on 2.13, because it's using sbt's classpath rather than the project's classpath, so it can only document the 2.12 compiler; that's https://github.com/scala/bug/issues/11642)

**Comment by SethTisue** [comment]
a note on the overall progress of this PR: the console bugs in 1.4.1 and 1.4.2 made me glad we didn't merge this already, but perhaps 1.4.3's the charm (after 2.13.4 is out, I mean)

**Comment by dwijnand** [comment]
sbt depends on the scala-compiler, so it looks like a straight regression to me.  Fortunately you can workaround it easily.

https://search.maven.org/artifact/org.scala-sbt/core-macros_2.12/1.4.3/jar

**Comment by eed3si9n** [comment]
> offhand, looking at the 1.4.3 notes, the only thing I see that vaguely seems potentially related is sbt/sbt#6085?

Likely you're right about sbt/sbt#6085 causing the issue, and changing the classpath on metabuild was not an intended consequence.

**Comment by eed3si9n** [comment]
There's an issue already https://github.com/sbt/sbt/issues/4452 from 2018 from the last time I implemented this with Coursier.

**Comment by SethTisue** [comment]
assuming Travis-CI likes it (Jenkins already does), I believe this is ready for merge.

**Comment by SethTisue** [comment]
@dwijnand I believe this is ready for merge.

**Comment by SethTisue** [comment]
oh wow, 1.4.4 just came out: https://github.com/sbt/sbt/releases/tag/v1.4.4

looking at the release notes, I don't see anything super important, though it certainly looks like nice fixes.

I actually suggest we merge this PR anyway, as is, and then I'll submit a separate PR with a 1.4.4 upgrade. I would actually prefer we wait at least a few days to make sure 1.4.4 is stable. (for instance, I'm about to run 1.4.4 through the community build.)

**Review by dwijnand — APPROVED** [review]
