### PR TITLE
A foreign definition induces ambiguity

### LINKED ISSUE #10662: Binding precedence not respected for enclosing package in unit
Even after #2458 the implementation still won't respect `p.X`, as it only looks for the first definition from enclosing scopes. The reference should be ambiguous because `p.q.X` is defined elsewhere.

```
package p {

  class X {
    override def toString() = "p.X"
  }

  package q {
    //import p.X  // "permanently hidden"
    object Test extends App {
      println(new X)
    }
  }
}
```
and in a different compilation unit:
```
package p.q

class X { 
  override def toString() = "p.q.X"
} 
// similarly for package object q { type X = other }
```

### PR DESCRIPTION
**Pull request by som-snytt**
A foreign definition can't shadow a definition
in the current unit. Also, an import that
could shadow the foreign definition can't
shadow the definition in the current unit.

Fixes scala/bug#10662

### CODE REVIEW

**Comment by som-snytt** [comment]
@SethTisue my other failed PR had a real bootstrap issue which I haven't fixed yet; I haven't checked this one yet... I've had bad flu, so it's all a blur...

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.13.x-validate-main/6460/ and https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.13.x-validate-main/6461/ also got wedged, so apparently there's a real problem.

feel better! I didn't get the new year's flu, just a new year's cold, but even the colds hit me pretty hard

**Comment by som-snytt** [comment]
`ABORTED. Took 934 min. Say /rebuild on PR...` Was that a record? Was I supposed to receive a special t-shirt signed by Jenkins?

I imagine he would scrawl with a sharpie: "LGTM! -- J"

**Comment by SethTisue** [comment]
PR title by Edward Gorey

**Comment by som-snytt** [comment]
I see @hrhino did a similar refactor, for a different purpose, so it's not an easy rebase.

**Comment by som-snytt** [comment]
@hrhino I had wanted encapsulation for that save/restore state, so I had a `DefinitionCursor` analogous to the one for imports; but I didn't apply that change to avoid any subtle performance difference.

The gist here is that just as it has to go looking for an ambiguating import, it has to go looking for an ambiguating definition if the definition we have is "defined in a different compilation unit", precedence level 4.

**Review by hrhino — APPROVED** [review]
It _looks_ right to me, but who can say? I may have changed this code, but I never claimed to understand it.

Do other people really write packagings this way? I'm glad this wound up being an error, because if you showed me `px_2.scala` and asked me what happens, I'd have to admit my insufficient Scala understanding. Does the puzzlers guy accept temporary puzzlers?

**Comment by som-snytt** [comment]
I think you hit the nail on the head: We're writing code totally wrong!

Remember the scene in Wrath of Khan where Ricardo Montalban chortles menacingly how the fleet is all one big happy family, and then proceeds to blow the Enterprise to pieces because its shields were down?

Package members are not your friends! Only trust what you see with your own eyes in the file you're editing, and then also verify.

If grumpy cat were still around, they would also ask, "Does the puzzlers guy accepts temporary puzzlers?"

**Review by adriaanm — APPROVED** [review]
`<font face="sharpie sans">` LGTM --a `</font> <!-- CSS who? -->`

**Comment by retronym** [comment]
Does this need a forward port to dotty?

**Comment by som-snytt** [comment]
There's also one more follow-up when answering that question. I also meant to gauge the spec's commitment on this point, especially after further experience and JDK modules, which may clarify if it solves more puzzlers than it creates.

**Comment by som-snytt** [comment]
I created a ticket for Dotty, and discovered that it picks `p.X` in both cases; Scala 2.13.0 picked the foreign `p.q.X` in one case, as I remembered, but `p.r.X`, the import of a locally defined symbol, in the other, which I'd forgotten. It's possible, of course, that `p.X` is just an opinionated choice.

**Comment by retronym** [comment]
I've noticed this bug fix comes up quite frequently when migrating 2.12 code bases to 2.13.

For the record here's a canonical example:

```scala
// /tmp/test.scala
package p1 {
  class C {
    def c_p1 = ""
  }
}

package p2 {
  class C {
    def c_p2 = ""
  }
}
```

```scala
package p2 {
  import p1._

  class test {
    new C().c_p2
  }
}
```

```
$ (export V=2.12.15 && (rm -rf /tmp/out/*; scalac --scala-version $V -d /tmp /tmp/test.scala && scalac --scala-version $V -cp /tmp -d /tmp  /tmp/client.scala))

$ (export V=2.13.8 && (rm -rf /tmp/out/*; scalac --scala-version $V -d /tmp /tmp/test.scala && scalac --scala-version $V -cp /tmp -d /tmp  /tmp/client.scala))

/tmp/client.scala:5: error: value c_p2 is not a member of p1.C
did you mean c_p1?
    new C().c_p2
            ^
1 error
```

A cross compatible version of `client.scala` is:

```scala
package p2 {
  import p1.{C => _, _}

  class test {
    new C().c_p2
  }
}
```

IntelliJ's presentation compiler works implements both the old and new behaviour, choosing which one based on the current Scala version: https://github.com/JetBrains/intellij-scala/commit/a427c20086023a4bcade3deb28483f4dd8a569a6

**Comment by som-snytt** [comment]
The Dotty ticket is https://github.com/lampepfl/dotty/issues/8059

3.x is same as 2.13 for the canonical example.

I commented on the Dotty ticket that for these tests, Dotty picks `p.X` ~for the first and `p.r.X` for the second, which is a change in behavior since the ticket was lodged.~ (Edit: no, it is `p.X` for both.)

```
➜  i8059 rm -rf /tmp/sandbox/*
zsh: sure you want to delete all 5 files in /tmp/sandbox [yn]? y
➜  i8059 scalac -d /tmp/sandbox x.scala t1.scala
➜  i8059 scala -cp /tmp/sandbox p.Test
p.X
➜  i8059 rm -rf /tmp/sandbox/*
zsh: sure you want to delete the only file in /tmp/sandbox [yn]? y
➜  i8059 scalac -d /tmp/sandbox x.scala t2.scala
➜  i8059 scala -cp /tmp/sandbox p.Test
p.X
```
