### PR TITLE
Usability: compiler suggests possible names in NotAMemberError

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes https://github.com/scala/bug/issues/10181

With this change, NotAMemberError checks for possible members under target with edit distance of 2 or 1. To avoid false positives, candidates with size <2 (`eq`, `ne`, `_1` etc) are filtered out.

```scala
scala> import scala.io.StdIn.{readline, readInt}
              ^
       error: value readline is not a member of object scala.io.StdIn
       did you mean readLine?

scala> import scala.io.stdin.{readLine => line}
                       ^
       error: object stdin is not a member of package io
       did you mean StdIn?

scala> import scala.sth
              ^
       error: object sth is not a member of package scala
       did you mean sys or math?
```

### note

See also `-Ysuggest-idents` (https://github.com/scala/scala/commit/3e9e4ecf360e6eda5c26f798abfcb9bb882cf772), which got axed apparently for possible ["performance impact"](https://github.com/scala/scala/commit/9b9fb2cad46041c6cf101ec436b643e3e922bd35). Unlike that, this is a bit more constrained because I am just looking up the members of `target`, I think.

### CODE REVIEW

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala [hunk 1]
```diff
@@ -340,21 +340,47 @@ trait ContextErrors {
...
+              case Some(sym) => "\nnote: %s exists, but it has no companion object.".format(sym)
+              case _         => ""
+            }
+            // find out all the names available under target within 2 edit distances
+            val alternatives: List[String] = companionSymbol match {
+              case Some(sym) => Nil
+              case _ =>
+                val threshold = 2
+                val x = name.toString
+                val names = target.nonPrivateMembers.toList.map(_.name.toString).distinct
```
Comment (olofwalker) [inline src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: `.toVector` instead ? I do not know the size of `nonPrivateMembers` but it sounds significant and a Vector would perform better.

**Comment by som-snytt** [comment]
This is great. I feel like I'm in one of those dystopian novels where the heroes go back in time to fix things, and now there is peace, harmony, and income equality.

I looked at t3118 just for fun. Suggesting `x` looked suspicious because `x` used to leak from `Predef` implicits. It's suggesting member `x` instead of `case class C` in `x.C()` or `new x.C()`, where the suggestion makes no possible sense.

Ideally, we'd advise only solutions that type check, but maybe there are some heuristics to apply, such as does it have an apply method if the wrong expr is an apply. Similarly for a new thing.

Even so, better selection is a win. "We have a fine selection of selections that may fulfill your needs. May I suggest `x`, or perhaps `y` or `z`?" Under `-Yobsequious-messages` or `-Xinveigle`.

**Comment by eed3si9n** [comment]
> This is great. I feel like I'm in one of those dystopian novels where the heroes go back in time to fix things, and now there is peace, harmony, and income equality.

Thank you :)

> I looked at t3118 just for fun. Suggesting `x` looked suspicious because `x` used to leak from `Predef` implicits. It's suggesting member `x` instead of `case class C` in `x.C()` or `new x.C()`, where the suggestion makes no possible sense.

In general, all 1 letter suggestions are shots in the dark, since they can be reached from any other 1 letter input with 2 edit distance. I probably should ignore them for now.

> Ideally, we'd advise only solutions that type check, but maybe there are some heuristics to apply, such as does it have an apply method if the wrong expr is an apply.

That would be amazing, but I don't have enough charges left on my portal gun.

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala (hunk 1 above)
Comment (eed3si9n) [reply src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: `target.nonPrivateMembers` returns [Scope](https://github.com/scala/scala/blob/2.13.x/src/reflect/scala/reflect/internal/Scopes.scala) containing method names and type names available under some package or object so the size would be around 20 most of the times? Scope implements only `.toList`, so if we were to use `Vector` I'd need to call `.toList.toVector`.

**Comment by som-snytt** [comment]
I was going to joke that 1-letter alternates should be within a certain distance on the keyboard, but then you'd have to know which keyboard. `-Ykb:dvorak`. I agree on saving ammo; wait until someone notices.

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala (hunk 1 above)
Comment (dwijnand) [reply src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: Different codebase, still scopes.. 😀

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala [hunk 2]
```diff
@@ -340,21 +340,48 @@ trait ContextErrors {
...
+              case Some(sym) => "\nnote: %s exists, but it has no companion object.".format(sym)
+              case _         => ""
+            }
+            // find out all the names available under target within 2 edit distances
+            lazy val alternatives: Vector[String] = {
+              val editThreshold = 2
+              val x = name.toString
+              if (x.size < 2) Vector()
+              else {
+                val names = target.nonPrivateMembers.toList.toVector.map(_.name.toString).distinct
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: `nonPrivateMembers.iterator.filterNot(m => m.isConstructor).map(_.name.decode).filter(_.length > 2).distinct.toList`

This does it in a single traversal. Using the decoded name to avoid the issue below:

```
scala> object C { def <= = 0 }
defined object C
warning: previously defined class C is not a companion to object C.
Companions must be defined together; you may wish to use :paste mode for this.

scala> C.lesseq
         ^
       error: value lesseq is not a member of object C
       did you mean $less$eq?
```

I think filtering short names also here makes sense. Doing it after decoding removes operators like `<=`.

I think it still includes too much, for example

```
scala> case class C(x: Int)
scala> typeOf[C].nonPrivateMembers.iterator.filterNot(m => m.isConstructor).map(_.name.decode).filter(_.length > 2).distinct.toVector
res32: scala.collection.immutable.Vector[String] = Vector(equals, toString, hashCode, canEqual, productIterator, productElement, productArity, productPrefix, copy$default$1, copy, $asInstanceOf, $isInstanceOf, synchronized, finalize, wait, notifyAll, notify, clone, getClass, asInstanceOf, isInstanceOf)
```
We should exclude `copy$default$1`, `$asInstanceOf`, `$isInstanceOf`. But filtering all of `m.isSynthetic` is too much

```
scala> typeOf[C].nonPrivateMembers.iterator.filterNot(m => m.isSynthetic || m.isConstructor).map(_.name.decode).filter(_.length > 2).distinct.toVector
res33: scala.collection.immutable.Vector[String] = Vector(synchronized, finalize, wait, notifyAll, notify, clone, getClass, asInstanceOf, isInstanceOf)
```
We lose `copy`, `hashCode`, ...

Maybe we can do it by character (`.contains("$")`)? Since we're using decoded names, `$` should only show up in names that are not supposed to be used by the user.

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala [hunk 3]
```diff
@@ -340,21 +340,48 @@ trait ContextErrors {
...
+        import util.{ EditDistance, StringUtil }
+        def errMsg: String = {
           val owner            = qual.tpe.typeSymbol
           val target           = qual.tpe.widen
           def targetKindString = if (owner.isTypeParameterOrSkolem) "type parameter " else ""
           def nameString       = decodeWithKind(name, owner)
           /* Illuminating some common situations and errors a bit further. */
           def addendum         = {
-            val companion = {
+            val companionSymbol: Option[Symbol] = {
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: We usually use `NoSymbol` instead of `None: Option[Symbol]`. Then we can also remove the pattern match below.

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala [hunk 4]
```diff
@@ -340,21 +340,48 @@ trait ContextErrors {
...
+              else None
+            }
+            val companion = companionSymbol match {
+              case Some(sym) => "\nnote: %s exists, but it has no companion object.".format(sym)
+              case _         => ""
+            }
+            // find out all the names available under target within 2 edit distances
+            lazy val alternatives: Vector[String] = {
+              val editThreshold = 2
+              val x = name.toString
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: should be `name.decode`

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala (hunk 2 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: You could also delay the `toList` until after the filters below

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala [hunk 5]
```diff
@@ -340,21 +340,48 @@ trait ContextErrors {
...
+              if (x.size < 2) Vector()
+              else {
+                val names = target.nonPrivateMembers.toList.toVector.map(_.name.toString).distinct
+                names filter { n =>
+                  EditDistance.levenshtein(n, x) <= editThreshold
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: We should do some pre-filtering, only compute the distance if `math.abs(n.length - x.length) <= 2`.

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala [hunk 6]
```diff
@@ -340,21 +340,48 @@ trait ContextErrors {
...
+                } filterNot { s =>
+                  (s == x) || EditDistance.excludeMethods(s)
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: This is cheaper than computing the distance, so should be done first

**Review by lrytz — COMMENTED** [review]
a few more comments

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala [hunk 7]
```diff
@@ -340,21 +340,47 @@ trait ContextErrors {
...
-        def errMsg = {
+        import util.{ EditDistance, StringUtil }
+        def errMsg: String = {
           val owner            = qual.tpe.typeSymbol
           val target           = qual.tpe.widen
           def targetKindString = if (owner.isTypeParameterOrSkolem) "type parameter " else ""
           def nameString       = decodeWithKind(name, owner)
           /* Illuminating some common situations and errors a bit further. */
           def addendum         = {
+            val companionSymbol: Symbol = {
```
Comment (retronym) [inline src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala:361]: Is this code ever/often called in type errors generated during failed branches of implicit search? If so, we should disable the (expensive) addendum creation. We recently did [something similar](https://github.com/scala/scala/pull/6612/files#diff-05c273d837c49f8b6278b19592a541beR101)

**Review by retronym — CHANGES_REQUESTED** [review]

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala (hunk 7 above)
Comment (eed3si9n) [reply src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala:361]: I am not sure if it's called in the implicit search.
Inside typedSelect (https://github.com/scala/scala/blob/2b49d718fd2ce034a5f450b2041013e2889591d0/src/compiler/scala/tools/nsc/typechecker/Typers.scala#L4969), `val qual1 = adaptToMemberWithArgs(tree, qual, name, mode)` happens at line 4988, which I am guessing is where implicit search is done. 
At line 5036, typedSelect calls `lookupInQualifier`, which can call `NotAMemberError`. Could that mean that we're ok?

An experiment I did was to add `sys.error(..)` in `alternatives` below, and then added

```scala
object Suggest {
  implicit class RichInt(val i: Int) {
    def flippity: Unit = ()
  }

  1.flippity
}
```

to `pos/implicits-new.scala` test, and it ran without blowing up.

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala [hunk 8]
```diff
@@ -340,21 +340,47 @@ trait ContextErrors {
...
-                  case NoSymbol => ""
-                  case sym      => "\nNote: %s exists, but it has no companion object.".format(sym)
-                }
+              if (companionSymbol == NoSymbol) ""
+              else s"\nnote: $companionSymbol exists, but it has no companion object."
+            }
+            // find out all the names available under target within 2 edit distances
+            lazy val alternatives: List[String] = {
+              val editThreshold = 2
+              val x = name.toString
```
Comment (lrytz) [inline src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: `name.decode`

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala [hunk 9]
```diff
@@ -340,21 +340,47 @@ trait ContextErrors {
...
+                  .distinct.toList
               }
-              else ""
+            }
+            val altStr: String = {
+              if (companionSymbol != NoSymbol) ""
+              else
+                alternatives match {
+                  case Nil => ""
+                  case xs  => "\ndid you mean " + StringUtil.oxford(xs, "or") + "?"
```
Comment (retronym) [inline src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: We should abbreviate this list if `xs.length` is unreasonably large.

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala [hunk 10]
```diff
@@ -340,21 +340,47 @@ trait ContextErrors {
...
+              else {
+                target.nonPrivateMembers.iterator
+                  .filterNot(m => m.isConstructor)
+                  .map(_.name.decode)
+                  .filter(n => (n.length > 2) &&
+                    (math.abs(n.length - x.length) <= editThreshold) &&
+                    (n != x) &&
+                    !n.contains("$") &&
+                    EditDistance.levenshtein(n, x) <= editThreshold)
+                  .distinct.toList
```
Comment (retronym) [inline src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala:387]: We should probably only suggest term/type names depending on whether `name` is a term/type name.

**Comment by retronym** [comment]
This reminds me of a solution I submitted to [Ruby Quiz way back in 2006](http://rubyquiz.com/quiz76.html)

> In deference to the style of the solutions I've read since discovering
> Ruby Quiz recently my solution includes obligatory (if gratuitous) use
> of (method|const)_missing :)
> ...
> 
> ```ruby
> ptus gtt_xeet.cllocet {|t| TexMtunegr::mgnue_txet(t)}.jion("\n" * 2)
> ```

👴

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala [hunk 11]
```diff
@@ -340,21 +340,47 @@ trait ContextErrors {
...
+              if (companionSymbol == NoSymbol) ""
+              else s"\nnote: $companionSymbol exists, but it has no companion object."
+            }
+            // find out all the names available under target within 2 edit distances
+            lazy val alternatives: List[String] = {
+              val editThreshold = 2
+              val x = name.toString
+              if (x.size < 2) Nil
+              else {
+                target.nonPrivateMembers.iterator
```
Comment (retronym) [inline src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: It would be nice to look at all members and filter by those that are accessible at the callsite's `Context`. We should them be careful to exclude fields:

```scala
.filterNot(m => nme.isLocalName(m.name)))
```

Comment (eed3si9n) [reply src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: Added https://github.com/scala/scala/pull/6711/commits/1e8ec90b59f8b8bf44dd58490e5d8f2b4ffdb433 to address the accessibility.

**Comment by lrytz** [comment]
Some test `.check` files need updating https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/2374/#showFailuresLink

**Comment by eed3si9n** [comment]
@lrytz 

> Some test .check files need updating https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/2374/#showFailuresLink

Yes. I've been only doing `partest --update-check  --neg`, but it seems like we've picked up a few suggestions from `run`.

```
scala> 1 -> 2
         ^
       error: value -> is not a member of Int
       did you mean >>>?
```

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala (hunk 7 above)
Comment (lrytz) [reply src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala:361]: Could run all of `partest --pos` and `-partest --run` with that patch? If that goes well, I think we don't need to add any guards.

**Review by lrytz — COMMENTED** [review]
This looks good to me otherwise!

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala (hunk 7 above)
Comment (eed3si9n) [reply src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala:361]: @lrytz Good call. I am seeing a bunch of errors, but they do not look like implicit searches. Most of the failures look like `spec-arrays-pos.log`:

```
error: Int $plus$eq List()
```

likely caused by something like `i += 1`.

Only other kind that I noticed that doesn't involve `$eq` is `t8013-pos.log` etc:

```
error: t8013.Perverse.Impervolator pImpl List()
```

where `pImpl` shows up as a macro implementation:

```scala
def p(args: Any*): String = macro pImpl
```

These occur seldom enough, so I think they are ok, but I'm going to put a guard for `x.endsWith("=")`.

**Comment by som-snytt** [comment]
Is it deemed not useful to provide at least as many suggestions as completions?

```
scala> import scala.io.StdIn.{readline, readInt}
              ^
       error: value readline is not a member of object scala.io.StdIn
       did you mean readLine?

scala> 42.isShole
          ^
       error: value isShole is not a member of Int

scala> 42.isWhole
res1: Boolean = true

scala> 42.is
isInfinite     isNaN           isValidByte   isValidLong       
isInfinity     isNegInfinity   isValidChar   isValidShort      
isInstanceOf   isPosInfinity   isValidInt    isWhole  
```
Folks working in Java are likely to do this:
```
scala> "".toShortOptional
          ^
       error: value toShortOptional is not a member of String

scala> class C { def toIntOption = Option(42) }
defined class C

scala> val c = new C
c: C = C@ddffa6c

scala> c.toIntOptional
         ^
       error: value toIntOptional is not a member of C
       did you mean toIntOption?

```
Yes! That's exactly what I meant!
```
scala> List(1).unzip2
               ^
       error: value unzip2 is not a member of List[Int]
       did you mean unzip or unzip3?

scala> List(1,2,3) reverse_:: List(4,5,6)
                   ^
       error: value reverse_:: is not a member of List[Int]
       did you mean reverse_:::?

scala> List(1).toSea
               ^
       error: value toSea is not a member of List[Int]
       did you mean toSeq or toSet?
```
List to sea means your ship is in trouble.

This is the one I wanted to test:
```
scala> new C().asshole
               ^
       error: value asshole is not a member of C
       did you mean isWhole?
```

**Comment by eed3si9n** [comment]
> Is it deemed not useful to provide at least as many suggestions as completions?

Wouldn't that require presentation compiler etc? Maybe we could work on that in another round of PR if that's feasible. I'd like to see this PR land on 2.13 if possible.

File: src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala [hunk 12]
```diff
@@ -339,22 +339,52 @@ trait ContextErrors {
...
-                  case sym      => "\nNote: %s exists, but it has no companion object.".format(sym)
-                }
+              if (companionSymbol == NoSymbol) ""
+              else s"\nnote: $companionSymbol exists, but it has no companion object."
+            }
+            // find out all the names available under target within 2 edit distances
+            lazy val alternatives: List[String] = {
+              val editThreshold = 2
+              val x = name.decode
+              if ((x.size < 2) || x.endsWith("=")) Nil
```
Comment (adriaanm) [inline src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: @retronym, I assume you meant adding `context.openImplicits.nonEmpty` to the if condition, so that we don't suggest alternatives when an implicit search is underway? With that, does this LGTY?

Comment (eed3si9n) [reply src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala]: Added 96e590d5ccd58a1bb179b4b742d91ca47ef95c19.

**Comment by lrytz** [comment]
Rebased on 2.13.x to make sure there are no semantic merge conflicts. I'll merge this once it goes green.

**Comment by lrytz** [comment]
Added file headers to the new files, and squashed.

**Comment by lrytz** [comment]
🎉  thank you, @eed3si9n!

**Comment by SethTisue** [comment]
this is very, very cool

**Comment by eed3si9n** [comment]
I am happy that this landed in time for 2.13.

**Comment by som-snytt** [comment]
I was going to say something maudlin about helping the end user, referencing cop shows where they help the victim or hospital shows where they help the patient, but anything I could add would sound histrionic.

Instead, I'll say I'm happy if @eed3si9n is happy, which is the best measure.

**Comment by smarter** [comment]
FWIW, dotty has had an implementation of something like this for a couple of years: https://github.com/lampepfl/dotty/blob/614265d779cd601de10edd23eea93598cd824c21//compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala#L310-L364 It'd be good to synchronize the two implementations.
